"""Generate the SRS -> code -> tests traceability matrix (IEC 62304 §5.1.1).

Sources of truth:
  - Requirements: headings of the form ``### SRS-001: Title`` in docs/regulatory/srs.md
  - Code:         any ``SRS-xxx`` mention in a comment/docstring under CODE_ROOTS
  - Tests:        ``@pytest.mark.requirement("SRS-xxx", ...)`` on test functions/classes

Usage (from the repo root or anywhere):
  python dsp/scripts/traceability.py          # rewrite docs/regulatory/traceability.md
  python dsp/scripts/traceability.py --check  # exit 1 if the file is stale or IDs are unknown
"""

from __future__ import annotations

import argparse
import ast
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SRS_FILE = REPO_ROOT / "docs" / "regulatory" / "srs.md"
OUTPUT_FILE = REPO_ROOT / "docs" / "regulatory" / "traceability.md"
CODE_ROOTS: list[tuple[Path, tuple[str, ...]]] = [
    (REPO_ROOT / "dsp" / "sinus_dsp", ("*.py",)),
    (REPO_ROOT / "firmware", ("*.c", "*.h")),
]
TEST_ROOTS = [REPO_ROOT / "dsp" / "tests"]

REQ_ID = re.compile(r"\bSRS-\d{3}\b")
REQ_HEADING = re.compile(r"^#{2,4}\s+(SRS-\d{3})\b[\s:—-]*(.*)$")


@dataclass
class Matrix:
    titles: dict[str, str]
    code: dict[str, set[str]]
    tests: dict[str, set[str]]


def rel(path: Path) -> str:
    return path.relative_to(REPO_ROOT).as_posix()


def parse_requirements() -> dict[str, str]:
    titles: dict[str, str] = {}
    if not SRS_FILE.exists():
        return titles
    for line in SRS_FILE.read_text(encoding="utf-8").splitlines():
        m = REQ_HEADING.match(line.strip())
        if m:
            titles[m.group(1)] = m.group(2).strip()
    return titles


def scan_code() -> dict[str, set[str]]:
    refs: dict[str, set[str]] = defaultdict(set)
    for root, patterns in CODE_ROOTS:
        if not root.exists():
            continue
        for pattern in patterns:
            for path in sorted(root.rglob(pattern)):
                text = path.read_text(encoding="utf-8")
                for lineno, line in enumerate(text.splitlines(), start=1):
                    for req in REQ_ID.findall(line):
                        refs[req].add(f"`{rel(path)}:{lineno}`")
    return refs


def _requirement_ids(node: ast.FunctionDef | ast.AsyncFunctionDef | ast.ClassDef) -> list[str]:
    ids: list[str] = []
    for deco in node.decorator_list:
        if (
            isinstance(deco, ast.Call)
            and isinstance(deco.func, ast.Attribute)
            and deco.func.attr == "requirement"
        ):
            ids.extend(
                a.value
                for a in deco.args
                if isinstance(a, ast.Constant) and isinstance(a.value, str)
            )
    return ids


def scan_tests() -> dict[str, set[str]]:
    refs: dict[str, set[str]] = defaultdict(set)

    def visit(body: list[ast.stmt], path: Path, prefix: str, inherited: list[str]) -> None:
        for node in body:
            if isinstance(node, ast.ClassDef | ast.FunctionDef | ast.AsyncFunctionDef):
                ids = inherited + _requirement_ids(node)
                name = f"{prefix}::{node.name}"
                if isinstance(node, ast.ClassDef):
                    visit(node.body, path, name, ids)
                elif node.name.startswith("test"):
                    for req in ids:
                        refs[req].add(f"`{name}`")

    for root in TEST_ROOTS:
        for path in sorted(root.rglob("test_*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            visit(tree.body, path, rel(path), [])
    return refs


def build() -> Matrix:
    return Matrix(titles=parse_requirements(), code=scan_code(), tests=scan_tests())


def render(m: Matrix) -> str:
    lines = [
        "# Traceability matrix",
        "",
        "<!-- Generated by dsp/scripts/traceability.py. Do not edit by hand. -->",
        "",
        "| Requirement | Title | Implemented in | Verified by |",
        "|---|---|---|---|",
    ]
    for req in sorted(m.titles):
        code = "<br>".join(sorted(m.code.get(req, ()))) or "—"
        tests = "<br>".join(sorted(m.tests.get(req, ()))) or "**none**"
        lines.append(f"| {req} | {m.titles[req]} | {code} | {tests} |")
    if not m.titles:
        lines.append("| — | _No requirements defined yet in `srs.md`_ | — | — |")

    untested = sorted(r for r in m.titles if not m.tests.get(r))
    unknown = unknown_ids(m)
    lines += ["", "## Gaps", ""]
    lines.append(f"- Requirements without tests: {', '.join(untested) or 'none'}")
    lines.append(f"- Unknown IDs referenced in code/tests: {', '.join(unknown) or 'none'}")
    return "\n".join(lines) + "\n"


def unknown_ids(m: Matrix) -> list[str]:
    return sorted((set(m.code) | set(m.tests)) - set(m.titles))


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write; fail if the committed matrix is stale or unknown IDs are referenced",
    )
    args = parser.parse_args()

    matrix = build()
    content = render(matrix)

    if args.check:
        ok = True
        current = OUTPUT_FILE.read_text(encoding="utf-8") if OUTPUT_FILE.exists() else ""
        if current != content:
            print(f"{rel(OUTPUT_FILE)} is stale: run python dsp/scripts/traceability.py")
            ok = False
        if unknown := unknown_ids(matrix):
            print(f"Unknown requirement IDs referenced: {', '.join(unknown)}")
            ok = False
        return 0 if ok else 1

    OUTPUT_FILE.write_text(content, encoding="utf-8", newline="\n")
    print(f"Wrote {rel(OUTPUT_FILE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
