"""Deterministic synthetic ECG of the golden-vector input set (architecture §7.2, §8.12).

SRS-015: the synthetic inputs are generated by the software from documented parameters:
sampling frequencies of 250 Hz and 360 Hz, heart rates of 40, 75 and 180 bpm, each without
interference (``clean``) and with the baseline wander and mains interference of SRS-010 at
50 Hz (``bw-mains50``) and at 60 Hz (``bw-mains60``). Each input lasts 30 s.

Each beat is the sum of five Gaussian waves (P, Q, R, S, T). The beats and their R-wave
centres are computed on integers, so that no floating-point rounding decides whether a beat
exists or where its centre lies.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Final

import numpy as np

from sinus_dsp._types import FloatArray, IndexArray
from sinus_dsp.errors import InvalidInputError

#: Duration of each synthetic input, in whole seconds.
SYNTHETIC_DURATION_S: Final = 30  # s
#: The sampling frequencies of the set, in Hz.
SYNTHETIC_FS_HZ: Final = (250.0, 360.0)
#: The heart rates of the set, in bpm.
SYNTHETIC_HEART_RATES_BPM: Final = (40, 75, 180)
#: The variants of the set: no interference, then baseline wander and mains interference at
#: 50 Hz and at 60 Hz.
SYNTHETIC_VARIANTS: Final = ("clean", "bw-mains50", "bw-mains60")
#: The events of the event inputs (architecture §13.9).
SYNTHETIC_EVENTS: Final = ("artefact", "small-beat", "held", "rate-change")

# Baseline wander and mains interference of the interference variants (SRS-010).
_BASELINE_WANDER_HZ: Final = 0.3
_BASELINE_WANDER_MV: Final = 1.0
_MAINS_MV: Final = 0.2
# Mains setting of each variant, in Hz, and whether the interference is added.
_VARIANT_MAINS_HZ: Final = {"clean": 50, "bw-mains50": 50, "bw-mains60": 60}
_CLEAN: Final = "clean"

# The five waves of a beat, in the order they are added: (offset from the R-wave centre in
# ms, amplitude in mV, width sigma in ms, whether the offset and the width scale with
# s = sqrt(RR / 1 s)).
_WAVES: Final = (
    (-200.0, 0.15, 25.0, True),  # P
    (-30.0, -0.10, 10.0, False),  # Q
    (0.0, 1.00, 10.0, False),  # R
    (30.0, -0.20, 10.0, False),  # S
    (280.0, 0.30, 45.0, True),  # T
)


@dataclass(frozen=True)
class SyntheticEcg:
    """One synthetic input of the golden-vector set (SRS-015).

    Attributes:
        input_id: Input identifier, ``syn-fs<fs>-hr<hr>-<variant>``, e.g.
            ``syn-fs360-hr075-bw-mains60``.
        fs_hz: Sampling frequency, 250.0 or 360.0 Hz.
        heart_rate_bpm: Heart rate, 40, 75 or 180 bpm.
        variant: ``clean``, ``bw-mains50`` or ``bw-mains60``.
        mains_hz: Mains setting of the input: 50 for ``clean`` and ``bw-mains50``, 60 for
            ``bw-mains60``.
        parameters: The generator parameters, as the ``input_parameters`` header value of a
            golden-vector file, e.g. ``duration_s=30;heart_rate_bpm=75;
            baseline_wander_hz=0.3;baseline_wander_mv=1.0;mains_hz=60;mains_mv=0.2``.
        signal_mv: The ECG in mV, ``30 * fs`` samples, float64.
        r_peaks: The true beat positions: the samples of the R-wave centres, int64.
    """

    input_id: str
    fs_hz: float
    heart_rate_bpm: int
    variant: str
    mains_hz: int
    parameters: str
    signal_mv: FloatArray
    r_peaks: IndexArray


def synthetic_ecg(fs_hz: float, heart_rate_bpm: int, variant: str) -> SyntheticEcg:
    """Generate one synthetic input of the golden-vector set.

    SRS-015: a synthetic ECG generated deterministically from documented parameters
    (architecture §7.2).

    - The input lasts 30 s: ``30 * fs`` samples at the instants ``t_n = n / fs``.
    - With ``hr`` the heart rate in bpm and ``fs`` the sampling frequency as integers, beat
      ``k`` (from 0) exists if ``60 * k <= 29 * hr``, and its R wave is centred on the sample
      ``r_k = (hr * (fs + 1) + 120 * k * fs) // (2 * hr)``. These are, exactly,
      ``0.5 + k * RR <= 29.5 s`` and ``r_k = floor((0.5 + k * RR) * fs + 0.5)`` with
      ``RR = 60 / hr`` seconds: 20 beats at 40 bpm, 37 at 75 bpm and 88 at 180 bpm.
    - Each beat is the sum of the Gaussian waves ``A * exp(-(t - t_c)**2 / (2 * sigma**2))``
      of the P, Q, R, S and T waves, centred at ``t_c = r_k / fs + offset``; the offsets and
      widths of P and T scale with ``s = sqrt(RR / 1 s)``. Each wave is evaluated on the whole
      time axis and added in increasing ``k``, in the order P, Q, R, S, T.
    - The interference variants then add the baseline wander
      ``1.0 mV * sin(2 * pi * 0.3 Hz * t)``, then the mains interference
      ``0.2 mV * sin(2 * pi * f * t)``, with f = 50 Hz for ``bw-mains50`` and 60 Hz for
      ``bw-mains60``. ``clean`` adds nothing.

    Args:
        fs_hz: Sampling frequency, 250 or 360 Hz (an ``int`` or a ``float``, not a ``bool``).
        heart_rate_bpm: Heart rate, 40, 75 or 180 bpm (an ``int``, not a ``bool``).
        variant: ``clean``, ``bw-mains50`` or ``bw-mains60``.

    Returns:
        The input, with its identifier, settings, parameters and true beat positions.

    Raises:
        InvalidInputError: If an argument is not one of the values of the set, naming the
            argument and its value.
    """
    if (
        isinstance(fs_hz, bool)
        or not isinstance(fs_hz, int | float)
        or fs_hz not in SYNTHETIC_FS_HZ
    ):
        raise InvalidInputError(f"fs_hz is not one of 250 Hz and 360 Hz: {fs_hz!r}")
    if (
        isinstance(heart_rate_bpm, bool)
        or not isinstance(heart_rate_bpm, int)
        or heart_rate_bpm not in SYNTHETIC_HEART_RATES_BPM
    ):
        raise InvalidInputError(
            f"heart_rate_bpm is not one of 40, 75 and 180 bpm: {heart_rate_bpm!r}"
        )
    if not isinstance(variant, str) or variant not in SYNTHETIC_VARIANTS:
        raise InvalidInputError(
            f"variant is not one of {', '.join(SYNTHETIC_VARIANTS)}: {variant!r}"
        )

    fs = int(fs_hz)
    hr = int(heart_rate_bpm)
    mains_hz = _VARIANT_MAINS_HZ[variant]
    n_samples = SYNTHETIC_DURATION_S * fs
    t = np.arange(n_samples) / float(fs_hz)

    r_peaks = np.array(_r_wave_centres(fs, hr), dtype=np.int64)
    scale = math.sqrt(60.0 / hr)
    signal: FloatArray = np.zeros(n_samples, dtype=np.float64)
    for r_k in r_peaks.tolist():
        for offset_ms, amplitude_mv, width_ms, scaled in _WAVES:
            centre_s = r_k / float(fs_hz) + (offset_ms * scale if scaled else offset_ms) / 1000.0
            sigma_s = (width_ms * scale if scaled else width_ms) / 1000.0
            signal = signal + amplitude_mv * np.exp(-((t - centre_s) ** 2) / (2.0 * sigma_s**2))

    if variant == _CLEAN:
        wander_mv = 0.0
        mains_mv = 0.0
    else:
        wander_mv = _BASELINE_WANDER_MV
        mains_mv = _MAINS_MV
        signal = signal + wander_mv * np.sin(2.0 * np.pi * _BASELINE_WANDER_HZ * t)
        signal = signal + mains_mv * np.sin(2.0 * np.pi * mains_hz * t)

    parameters = (
        f"duration_s={SYNTHETIC_DURATION_S};heart_rate_bpm={hr};"
        f"baseline_wander_hz={_BASELINE_WANDER_HZ!r};baseline_wander_mv={wander_mv!r};"
        f"mains_hz={mains_hz};mains_mv={mains_mv!r}"
    )
    return SyntheticEcg(
        input_id=f"syn-fs{fs}-hr{hr:03d}-{variant}",
        fs_hz=float(fs_hz),
        heart_rate_bpm=hr,
        variant=variant,
        mains_hz=mains_hz,
        parameters=parameters,
        signal_mv=signal,
        r_peaks=r_peaks,
    )


def synthetic_set() -> tuple[SyntheticEcg, ...]:
    """Return the 18 synthetic inputs of the golden-vector set.

    SRS-015: every combination of the sampling frequencies (250 Hz, 360 Hz), the heart rates
    (40, 75, 180 bpm) and the variants (``clean``, ``bw-mains50``, ``bw-mains60``), ordered
    by sampling frequency, then heart rate, then variant, each in the order of its constant.
    """
    return tuple(
        synthetic_ecg(fs_hz, heart_rate_bpm, variant)
        for fs_hz in SYNTHETIC_FS_HZ
        for heart_rate_bpm in SYNTHETIC_HEART_RATES_BPM
        for variant in SYNTHETIC_VARIANTS
    )


def synthetic_event_ecg(fs_hz: float, event: str) -> SyntheticEcg:
    """Generate one synthetic event input (architecture §13.9).

    SRS-033: an ECG built from the waveform of :func:`synthetic_ecg` with one event that makes
    the detection re-learn (``artefact``), find a beat by search-back (``small-beat``), hold
    the input (``held``) or change the rate (``rate-change``). The beats are lists of
    ``(t_ms, rr_s, scale)``; their positions are computed on integers,
    ``r = (t_ms * fs + 500) // 1000``, and the reference beats are all of them.

    Args:
        fs_hz: Sampling frequency, 250 or 360 Hz (an ``int`` or a ``float``, not a ``bool``).
        event: One of :data:`SYNTHETIC_EVENTS`.

    Returns:
        The input, with ``variant`` the event name, ``heart_rate_bpm`` 75 and ``mains_hz`` 50.

    Raises:
        InvalidInputError: If an argument is not one of the values of the set.
    """
    if (
        isinstance(fs_hz, bool)
        or not isinstance(fs_hz, int | float)
        or fs_hz not in SYNTHETIC_FS_HZ
    ):
        raise InvalidInputError(f"fs_hz is not one of 250 Hz and 360 Hz: {fs_hz!r}")
    if not isinstance(event, str) or event not in SYNTHETIC_EVENTS:
        raise InvalidInputError(f"event is not one of {', '.join(SYNTHETIC_EVENTS)}: {event!r}")

    fs = int(fs_hz)
    regular = [(500 + 800 * k, 0.8, 1.0) for k in range(49)]
    duration_s = 40
    parameters = f"duration_s=40;event={event};heart_rate_bpm=75;"
    held_from_ms = 15000
    held_ms = 6000
    if event == "artefact":
        regular[12] = (regular[12][0], 0.8, 20.0)
        beats = regular
        parameters += "scaled_beat_ms=10100;scale=20.0;mains_hz=50"
    elif event == "small-beat":
        regular[12] = (regular[12][0], 0.8, 0.4)
        beats = regular
        parameters += "scaled_beat_ms=10100;scale=0.4;mains_hz=50"
    elif event == "held":
        beats = regular
        parameters += f"held_from_ms={held_from_ms};held_ms={held_ms};mains_hz=50"
    else:
        duration_s = 44
        beats = (
            [(500 + 800 * k, 0.8, 1.0) for k in range(15)]
            + [(11700 + 2400 * j, 2.4, 1.0) for j in range(1, 9)]
            + [(30900 + 800 * j, 0.8, 1.0) for j in range(1, 16)]
        )
        parameters = (
            "duration_s=44;event=rate-change;heart_rates_bpm=75/25/75;"
            "changes_ms=11700/30900;mains_hz=50"
        )

    n_samples = duration_s * fs
    t = np.arange(n_samples) / float(fs_hz)
    r_peaks = np.array([(t_ms * fs + 500) // 1000 for t_ms, _rr, _scale in beats], dtype=np.int64)
    signal: FloatArray = np.zeros(n_samples, dtype=np.float64)
    for r_k, (_t_ms, rr_s, beat_scale) in zip(r_peaks.tolist(), beats, strict=True):
        scale = math.sqrt(rr_s)
        for offset_ms, amplitude_mv, width_ms, scaled in _WAVES:
            centre_s = r_k / float(fs_hz) + (offset_ms * scale if scaled else offset_ms) / 1000.0
            sigma_s = (width_ms * scale if scaled else width_ms) / 1000.0
            signal = signal + (amplitude_mv * beat_scale) * np.exp(
                -((t - centre_s) ** 2) / (2.0 * sigma_s**2)
            )
    if event == "held":
        first = (held_from_ms * fs + 500) // 1000
        end = ((held_from_ms + held_ms) * fs + 500) // 1000
        signal[first:end] = signal[first]

    return SyntheticEcg(
        input_id=f"syn-fs{fs}-event-{event}",
        fs_hz=float(fs_hz),
        heart_rate_bpm=75,
        variant=event,
        mains_hz=50,
        parameters=parameters,
        signal_mv=signal,
        r_peaks=r_peaks,
    )


def synthetic_event_set() -> tuple[SyntheticEcg, ...]:
    """Return the 8 synthetic event inputs: by sampling frequency, then event (§13.9).

    SRS-033: the inputs that exercise the marks, paths, statuses and windows that the clean
    rhythms of :func:`synthetic_set` do not.
    """
    return tuple(
        synthetic_event_ecg(fs_hz, event) for fs_hz in SYNTHETIC_FS_HZ for event in SYNTHETIC_EVENTS
    )


def _r_wave_centres(fs: int, hr: int) -> list[int]:
    """The samples ``r_k`` of the R-wave centres, computed on integers (architecture §7.2).

    Beat ``k`` exists if ``60 * k <= (30 - 1) * hr``, i.e. ``0.5 + k * RR <= 29.5 s``.
    """
    last_k = (SYNTHETIC_DURATION_S - 1) * hr // 60
    return [(hr * (fs + 1) + 120 * k * fs) // (2 * hr) for k in range(last_k + 1)]
