"""Unit tests of the rendering of the validation reports, on results built by hand."""

import dataclasses
import random
import re

import pytest

from sinus_dsp.data.physionet import Database, VerificationResult
from sinus_dsp.errors import InvalidInputError
from sinus_dsp.evaluation.metrics import RecordCounts, aggregate_statistics
from sinus_dsp.evaluation.noise_stress import (
    NOISE_STRESS_RECORDS,
    NoiseStressResults,
    SnrStatistics,
    snr_db,
)
from sinus_dsp.evaluation.report import render_full_report, render_subset_report
from sinus_dsp.evaluation.run import EvaluationSettings, RecordEvaluation, ValidationResults

MITDB_VERIFICATION = VerificationResult(
    Database("mitdb", "1.0.0", "Fixture Arrhythmia Database", "a" * 64),
    None,
    ("100.dat", "100.hea", "RECORDS"),
)
NSTDB_VERIFICATION = VerificationResult(
    Database("nstdb", "1.0.0", "Fixture Noise Database", "b" * 64), None, ("118e24.dat",)
)
DEFAULT_SETTINGS = EvaluationSettings()


def evaluation(
    name: str,
    tp: int,
    fn: int,
    fp: int,
    *,
    signal: str = "MLII",
    fs_hz: float = 360.0,
    vf: tuple[int, int, int, int, int] = (0, 0, 0, 0, 0),
    flutter: int = 0,
) -> RecordEvaluation:
    """A record evaluation; ``vf`` is (episodes, from 5:00, samples, reference, detections)."""
    return RecordEvaluation(
        record=name,
        signal_name=signal,
        fs_hz=fs_hz,
        counts=RecordCounts(name, tp, fn, fp),
        vf_episodes=vf[0],
        vf_episodes_scored=vf[1],
        vf_samples_scored=vf[2],
        reference_excluded=vf[3],
        detections_excluded=vf[4],
        flutter_waves_outside_vf=flutter,
    )


RECORDS = (
    evaluation("100", 793, 7, 0),  # Se 99.125 exactly: two decimals give 99.12
    evaluation("102", 3, 0, 0, signal="V5", flutter=2),
    evaluation("105", 0, 0, 4),  # Se not defined
    evaluation("118", 2000, 5, 10),
    evaluation("119", 1500, 1, 2),
    evaluation("207", 1000, 30, 20, vf=(6, 1, 35245, 0, 3)),
)


def noise_stress(
    records: tuple[RecordEvaluation, ...] = RECORDS, *, snr_order: tuple[int, ...] | None = None
) -> NoiseStressResults:
    noisy = tuple(
        evaluation(name, 100 - i, i, 2 * i) for i, name in enumerate(NOISE_STRESS_RECORDS)
    )
    snrs = snr_order if snr_order is not None else (24, 18, 12, 6, 0, -6)
    by_snr = tuple(
        SnrStatistics(
            snr,
            aggregate_statistics([entry.counts for entry in noisy if snr_db(entry.record) == snr]),
        )
        for snr in snrs
    )
    clean = aggregate_statistics(
        [entry.counts for entry in records if entry.record in ("118", "119")]
    )
    return NoiseStressResults(NSTDB_VERIFICATION, noisy, by_snr, clean)


def full_results(
    records: tuple[RecordEvaluation, ...] = RECORDS,
    settings: EvaluationSettings = DEFAULT_SETTINGS,
) -> ValidationResults:
    return ValidationResults(
        software_version="0.0.1",
        settings=settings,
        mitdb=MITDB_VERIFICATION,
        records=records,
        noise_stress=noise_stress(records),
        subset=False,
    )


def subset_results(records: tuple[RecordEvaluation, ...] = RECORDS) -> ValidationResults:
    return dataclasses.replace(full_results(records), noise_stress=None, subset=True)


# The full report of RECORDS, checked by hand: Se of 100 = 79300 / 800 = 99.125 is written
# 99.12 (correctly rounded from the float64 value, which is exact); gross 5296, 43, 36 gives
# Se 529600 / 5339 = 99.195 and +P 529600 / 5332 = 99.325; the Se average is over the 5
# defined values; the +P tie at 100.00 between 100 and 102 is ordered by record name; record
# 207 has 35245 samples from 5:00 at 360 Hz, 97.9 s.
EXPECTED_FULL_REPORT = (
    (
        "\n".join(
            [
                "# QRS detection: EC57 beat-by-beat evaluation",
                "",
                "Technical evaluation only. Sinus is not a medical device; these results are not "
                "a clinical validation.",
                "",
                "Generated by dsp/scripts/validate.py; do not edit by hand.",
                "",
                "## Software, data and settings",
                "",
                "| Item | Value |",
                "|---|---|",
                "| Software | sinus-dsp 0.0.1 |",
                "| Database | Fixture Arrhythmia Database, version 1.0.0 |",
                "| Verification | verified: 3 files match the published SHA-256 checksum list "
                "(SHA256SUMS.txt, SHA-256 {A}) |",
                "| Records | 6 |",
                "| Signal | first stored signal of each record (channel 0) |",
                "| Mains interference filter | 60 Hz |",
                "| Matching | EC57 beat by beat, pairing rules of the WFDB comparator bxb; match "
                "window 150 ms; first 5 min of each record not scored; ventricular flutter and "
                "fibrillation episodes not scored |",
                "",
                "## Performance targets",
                "",
                "| Statistic | Value (%) | Target (%) | Result |",
                "|---|---:|---|---|",
                "| Gross Se | 99.19 | ≥ 99.50 | fail |",
                "| Gross +P | 99.32 | ≥ 99.50 | fail |",
                "",
                "## Results per record",
                "",
                "| Record | Signal | TP | FN | FP | Se (%) | +P (%) |",
                "|---|---|---:|---:|---:|---:|---:|",
                "| 100 | MLII | 793 | 7 | 0 | 99.12 | 100.00 |",
                "| 102 | V5 | 3 | 0 | 0 | 100.00 | 100.00 |",
                "| 105 | MLII | 0 | 0 | 4 | not defined | 0.00 |",
                "| 118 | MLII | 2000 | 5 | 10 | 99.75 | 99.50 |",
                "| 119 | MLII | 1500 | 1 | 2 | 99.93 | 99.87 |",
                "| 207 | MLII | 1000 | 30 | 20 | 97.09 | 98.04 |",
                "| Gross |  | 5296 | 43 | 36 | 99.19 | 99.32 |",
                "| Average |  |  |  |  | 99.18 | 82.90 |",
                "",
                "The averages are the means of the defined per-record values: Se is defined for 5"
                " of 6 records, +P for 6 of 6 records.",
                "",
                "## Lowest sensitivity",
                "",
                "The records with the lowest defined Se, at most 5, lowest first; ties are "
                "ordered by record name.",
                "",
                "| Rank | Record | Se (%) |",
                "|---:|---|---:|",
                "| 1 | 207 | 97.09 |",
                "| 2 | 100 | 99.12 |",
                "| 3 | 118 | 99.75 |",
                "| 4 | 119 | 99.93 |",
                "| 5 | 102 | 100.00 |",
                "",
                "## Lowest positive predictivity",
                "",
                "The records with the lowest defined +P, at most 5, lowest first; ties are "
                "ordered by record name.",
                "",
                "| Rank | Record | +P (%) |",
                "|---:|---|---:|",
                "| 1 | 105 | 0.00 |",
                "| 2 | 207 | 98.04 |",
                "| 3 | 118 | 99.50 |",
                "| 4 | 119 | 99.87 |",
                "| 5 | 100 | 100.00 |",
                "",
                "## Segments not scored",
                "",
                "The first 5 min of each record are not scored. Ventricular flutter and "
                "fibrillation episodes are not scored either. The durations and counts below "
                "cover the part of each record from 5:00 to its end.",
                "",
                "| Record | Episodes in the record | Episodes from 5:00 | Duration from 5:00 (s) "
                "| Reference beats not scored | Detections not scored |",
                "|---|---:|---:|---:|---:|---:|",
                "| 207 | 6 | 1 | 97.9 | 0 | 3 |",
                "",
                "Flutter-wave annotations outside ventricular flutter and fibrillation episodes, "
                "in all records: 2.",
                "",
                "## Noise stress test",
                "",
                "| Item | Value |",
                "|---|---|",
                "| Database | Fixture Noise Database, version 1.0.0 |",
                "| Verification | verified: 1 files match the published SHA-256 checksum list "
                "(SHA256SUMS.txt, SHA-256 {B}) |",
                "",
                "### Results per record",
                "",
                "| Record | SNR (dB) | TP | FN | FP | Se (%) | +P (%) |",
                "|---|---:|---:|---:|---:|---:|---:|",
                "| 118e24 | 24 | 100 | 0 | 0 | 100.00 | 100.00 |",
                "| 118e18 | 18 | 99 | 1 | 2 | 99.00 | 98.02 |",
                "| 118e12 | 12 | 98 | 2 | 4 | 98.00 | 96.08 |",
                "| 118e06 | 6 | 97 | 3 | 6 | 97.00 | 94.17 |",
                "| 118e00 | 0 | 96 | 4 | 8 | 96.00 | 92.31 |",
                "| 118e_6 | -6 | 95 | 5 | 10 | 95.00 | 90.48 |",
                "| 119e24 | 24 | 94 | 6 | 12 | 94.00 | 88.68 |",
                "| 119e18 | 18 | 93 | 7 | 14 | 93.00 | 86.92 |",
                "| 119e12 | 12 | 92 | 8 | 16 | 92.00 | 85.19 |",
                "| 119e06 | 6 | 91 | 9 | 18 | 91.00 | 83.49 |",
                "| 119e00 | 0 | 90 | 10 | 20 | 90.00 | 81.82 |",
                "| 119e_6 | -6 | 89 | 11 | 22 | 89.00 | 80.18 |",
                "",
                "### Results per SNR",
                "",
                "| SNR (dB) | TP | FN | FP | Gross Se (%) | Gross +P (%) |",
                "|---|---:|---:|---:|---:|---:|",
                "| 24 | 194 | 6 | 12 | 97.00 | 94.17 |",
                "| 18 | 192 | 8 | 16 | 96.00 | 92.31 |",
                "| 12 | 190 | 10 | 20 | 95.00 | 90.48 |",
                "| 6 | 188 | 12 | 24 | 94.00 | 88.68 |",
                "| 0 | 186 | 14 | 28 | 93.00 | 86.92 |",
                "| -6 | 184 | 16 | 32 | 92.00 | 85.19 |",
                "| no added noise (Fixture Arrhythmia Database, records 118 and 119) | 3500 | 6 |"
                " 12 | 99.83 | 99.66 |",
                "",
                "No pass threshold is set for these results (OP-031).",
            ]
        )
        + "\n"
    )
    .replace("{A}", "a" * 64)
    .replace("{B}", "b" * 64)
)

STATEMENT = (
    "Technical evaluation only. Sinus is not a medical device; "
    "these results are not a clinical validation."
)


def headings(text: str) -> list[str]:
    return [line for line in text.split("\n") if line.startswith("#")]


def line_after(text: str, start: str) -> list[str]:
    """The lines of the table or paragraph that follows the line starting with ``start``."""
    lines = text.split("\n")
    index = next(i for i, line in enumerate(lines) if line.startswith(start))
    block: list[str] = []
    for line in lines[index + 2 :]:
        if not line:
            break
        block.append(line)
    return block


# --- full report ----------------------------------------------------------------------------


def test_full_report_as_checked_by_hand() -> None:
    assert render_full_report(full_results()) == EXPECTED_FULL_REPORT


def test_full_report_sections_in_order() -> None:
    assert headings(render_full_report(full_results())) == [
        "# QRS detection: EC57 beat-by-beat evaluation",
        "## Software, data and settings",
        "## Performance targets",
        "## Results per record",
        "## Lowest sensitivity",
        "## Lowest positive predictivity",
        "## Segments not scored",
        "## Noise stress test",
        "### Results per record",
        "### Results per SNR",
    ]


@pytest.mark.parametrize("render", [render_full_report, render_subset_report])
def test_text_format(render: object) -> None:
    results = full_results() if render is render_full_report else subset_results()
    assert callable(render)
    text = render(results)
    assert isinstance(text, str)
    assert text.endswith("\n")
    assert not text.endswith("\n\n")
    assert "\r" not in text
    assert "\t" not in text
    assert all(line == line.rstrip() for line in text.split("\n"))
    assert "\n\n\n" not in text
    # The statement is its own paragraph.
    assert f"\n\n{STATEMENT}\n\n" in text
    # No requirement ID, no date or time, no path of this machine.
    assert re.search(r"SRS-\d", text) is None
    assert re.search(r"\d{4}-\d{2}-\d{2}", text) is None
    assert re.search(r"\d{1,2}:\d{2}:\d{2}", text) is None
    assert "\\" not in text
    text.encode("utf-8")


def test_report_does_not_depend_on_the_order_of_the_records() -> None:
    shuffled = list(RECORDS)
    random.Random(3).shuffle(shuffled)
    assert render_full_report(full_results(tuple(shuffled))) == EXPECTED_FULL_REPORT
    assert render_full_report(full_results()) == render_full_report(full_results())


def test_snr_rows_in_decreasing_order_whatever_the_order_given() -> None:
    results = dataclasses.replace(
        full_results(), noise_stress=noise_stress(snr_order=(-6, 0, 24, 6, 18, 12))
    )
    assert render_full_report(results) == EXPECTED_FULL_REPORT


def test_targets_pass_at_99_50_percent() -> None:
    records = (evaluation("100", 199, 1, 1), evaluation("118", 0, 0, 0), evaluation("119", 0, 0, 0))
    text = render_full_report(full_results(records))
    assert line_after(text, "## Performance targets")[2:] == [
        "| Gross Se | 99.50 | ≥ 99.50 | pass |",
        "| Gross +P | 99.50 | ≥ 99.50 | pass |",
    ]


def test_targets_just_below_99_50_percent_fail() -> None:
    # 1990 / 2000 = 99.50 %; 1989 / 1999 = 99.4997 % is written 99.50 but fails.
    records = (evaluation("118", 1989, 10, 10), evaluation("119", 0, 0, 0))
    text = render_full_report(full_results(records))
    assert line_after(text, "## Performance targets")[2:] == [
        "| Gross Se | 99.50 | ≥ 99.50 | fail |",
        "| Gross +P | 99.50 | ≥ 99.50 | fail |",
    ]


def test_targets_not_defined_fail() -> None:
    records = (evaluation("118", 0, 0, 0), evaluation("119", 0, 0, 0))
    text = render_full_report(full_results(records))
    assert line_after(text, "## Performance targets")[2:] == [
        "| Gross Se | not defined | ≥ 99.50 | fail |",
        "| Gross +P | not defined | ≥ 99.50 | fail |",
    ]
    table = line_after(text, "## Results per record")
    assert table[-2:] == [
        "| Gross |  | 0 | 0 | 0 | not defined | not defined |",
        "| Average |  |  |  |  | not defined | not defined |",
    ]
    assert "Se is defined for 0 of 2 records, +P for 0 of 2 records." in text
    assert "## Lowest sensitivity\n\nNo record has a defined Se.\n\n" in text
    assert "## Lowest positive predictivity\n\nNo record has a defined +P.\n\n" in text


def test_lowest_values_ties_by_record_name_and_at_most_five() -> None:
    records = (
        evaluation("201", 99, 1, 0),
        evaluation("118", 99, 1, 0),
        evaluation("119", 98, 2, 0),
        evaluation("200", 99, 1, 0),
        evaluation("101", 99, 1, 0),
        evaluation("102", 99, 1, 0),
        evaluation("103", 50, 0, 50),
    )
    text = render_full_report(full_results(records))
    assert line_after(text, "The records with the lowest defined Se") == [
        "| Rank | Record | Se (%) |",
        "|---:|---|---:|",
        "| 1 | 119 | 98.00 |",
        "| 2 | 101 | 99.00 |",
        "| 3 | 102 | 99.00 |",
        "| 4 | 118 | 99.00 |",
        "| 5 | 200 | 99.00 |",
    ]
    assert line_after(text, "The records with the lowest defined +P") == [
        "| Rank | Record | +P (%) |",
        "|---:|---|---:|",
        "| 1 | 103 | 50.00 |",
        "| 2 | 101 | 100.00 |",
        "| 3 | 102 | 100.00 |",
        "| 4 | 118 | 100.00 |",
        "| 5 | 119 | 100.00 |",
    ]


def test_lowest_values_are_ranked_on_the_values_not_on_the_rounded_text() -> None:
    # 99.124 % and 99.121 % are both written 99.12; the lower value comes first.
    records = (
        evaluation("100", 99124, 876, 0),
        evaluation("118", 99121, 879, 0),
        evaluation("119", 1, 0, 0),
    )
    text = render_full_report(full_results(records))
    assert line_after(text, "The records with the lowest defined Se")[2:4] == [
        "| 1 | 118 | 99.12 |",
        "| 2 | 100 | 99.12 |",
    ]


def test_fewer_than_five_defined_values() -> None:
    records = (evaluation("118", 1, 1, 0), evaluation("119", 0, 0, 3))
    text = render_full_report(full_results(records))
    assert line_after(text, "The records with the lowest defined Se")[2:] == ["| 1 | 118 | 50.00 |"]
    assert line_after(text, "The records with the lowest defined +P")[2:] == [
        "| 1 | 119 | 0.00 |",
        "| 2 | 118 | 100.00 |",
    ]


def test_percentages_are_correctly_rounded() -> None:
    # 2 / 3 = 66.666...; 1 / 8 = 12.5 exactly; 99.995 is not exact in binary.
    records = (
        evaluation("118", 2, 1, 7),  # Se 66.67, +P 22.22
        evaluation("119", 1, 7, 0),  # Se 12.50
    )
    table = line_after(render_full_report(full_results(records)), "## Results per record")
    assert table[2:4] == [
        "| 118 | MLII | 2 | 1 | 7 | 66.67 | 22.22 |",
        "| 119 | MLII | 1 | 7 | 0 | 12.50 | 100.00 |",
    ]
    assert f"{100 * 19999 / 20000:.2f}" == "100.00"


def test_settings_other_than_the_defaults_are_stated() -> None:
    text = render_full_report(full_results(settings=EvaluationSettings(channel=1, mains_hz=50)))
    assert "| Signal | channel 1 of each record |" in text
    assert "| Mains interference filter | 50 Hz |" in text


def test_version_database_and_verification_of_a_subset_selection() -> None:
    verification = VerificationResult(
        Database("mitdb", "2.0.0", "Other | Database", "c" * 64), ("100", "118"), ("100.dat",)
    )
    results = dataclasses.replace(full_results(), mitdb=verification, software_version="9.8.7")
    text = render_full_report(results)
    assert "| Software | sinus-dsp 9.8.7 |" in text
    assert "| Database | Other \\| Database, version 2.0.0 |" in text
    assert (
        "| Verification | verified: 1 files match the published SHA-256 checksum list "
        f"(SHA256SUMS.txt, SHA-256 {'c' * 64}); records 100, 118 |"
    ) in text


# --- segments not scored --------------------------------------------------------------------


def test_segments_not_scored_rows_sorted_with_episodes_only() -> None:
    records = (
        evaluation("207", 1, 0, 0, vf=(6, 1, 35245, 0, 3)),
        evaluation("119", 1, 0, 0),
        evaluation("118", 1, 0, 0, fs_hz=250.0, vf=(1, 1, 1000, 4, 2), flutter=1),
        evaluation("106", 1, 0, 0, vf=(2, 0, 0, 0, 0), flutter=5),
    )
    text = render_full_report(full_results(records))
    assert line_after(text, "The first 5 min of each record are not scored.") == [
        "| Record | Episodes in the record | Episodes from 5:00 | Duration from 5:00 (s) "
        "| Reference beats not scored | Detections not scored |",
        "|---|---:|---:|---:|---:|---:|",
        "| 106 | 2 | 0 | 0.0 | 0 | 0 |",
        "| 118 | 1 | 1 | 4.0 | 4 | 2 |",
        "| 207 | 6 | 1 | 97.9 | 0 | 3 |",
    ]
    assert (
        "Flutter-wave annotations outside ventricular flutter and fibrillation episodes, "
        "in all records: 6."
    ) in text


def test_no_episode_in_any_record() -> None:
    records = (evaluation("118", 1, 0, 0), evaluation("119", 1, 0, 0))
    text = render_full_report(full_results(records))
    section = text.split("## Segments not scored\n\n", 1)[1].split("\n\n## ", 1)[0]
    assert section.split("\n\n") == [
        "The first 5 min of each record are not scored. Ventricular flutter and fibrillation "
        "episodes are not scored either. The durations and counts below cover the part of "
        "each record from 5:00 to its end.",
        "No ventricular flutter or fibrillation episode is annotated in these records.",
        "Flutter-wave annotations outside ventricular flutter and fibrillation episodes, in "
        "all records: 0.",
    ]


def test_duration_is_rounded_to_one_decimal() -> None:
    records = (
        evaluation("118", 1, 0, 0, vf=(1, 1, 18, 0, 0)),  # 0.05 s at 360 Hz
        evaluation("119", 1, 0, 0, vf=(1, 1, 125, 0, 0), fs_hz=250.0),  # 0.5 s
    )
    table = line_after(render_full_report(full_results(records)), "The first 5 min")
    assert [row.split(" | ")[3] for row in table[2:]] == [f"{18 / 360:.1f}", "0.5"]


# --- subset report --------------------------------------------------------------------------


def test_subset_report_sections_and_paragraph() -> None:
    text = render_subset_report(subset_results())
    assert headings(text) == [
        "# QRS detection: EC57 subset report for regression checking",
        "## Software, data and settings",
        "## Results per record",
        "## Lowest sensitivity",
        "## Lowest positive predictivity",
        "## Segments not scored",
    ]
    assert text.startswith(
        "# QRS detection: EC57 subset report for regression checking\n\n"
        f"{STATEMENT}\n\n"
        "This report covers records 100, 102, 105, 118, 119 and 207 of the Fixture "
        "Arrhythmia Database. It is a regression check run on every change, not the "
        "performance evaluation against the targets, which uses all 48 records "
        "(qrs-ec57-report.md).\n\n"
        "Generated by dsp/scripts/subset_check.py; do not edit by hand.\n\n"
        "## Software, data and settings\n\n"
    )
    assert "Performance targets" not in text
    assert "Noise stress" not in text
    assert "OP-031" not in text


def test_subset_report_shares_the_sections_of_the_full_report() -> None:
    full = render_full_report(full_results())
    subset = render_subset_report(subset_results())
    shared = full.split("## Software, data and settings", 1)[1]
    shared_sections = (
        shared.split("## Performance targets", 1)[0]
        + ("## Results per record" + shared.split("## Results per record", 1)[1]).split(
            "## Noise stress test", 1
        )[0]
    )
    assert (
        subset.split("## Software, data and settings", 1)[1] == shared_sections.rstrip("\n") + "\n"
    )


@pytest.mark.parametrize(
    ("names", "expected"),
    [
        (("100",), "This report covers record 100 of the"),
        (("100", "207"), "This report covers records 100 and 207 of the"),
        (("207", "100", "105"), "This report covers records 100, 105 and 207 of the"),
    ],
)
def test_subset_paragraph_names_the_records(names: tuple[str, ...], expected: str) -> None:
    records = tuple(evaluation(name, 1, 0, 0) for name in names)
    assert expected in render_subset_report(subset_results(records))


# --- misuse ---------------------------------------------------------------------------------


def test_full_report_needs_the_whole_evaluation() -> None:
    with pytest.raises(InvalidInputError, match="needs the results of the whole evaluation"):
        render_full_report(subset_results())
    with pytest.raises(InvalidInputError, match="with the noise stress test"):
        render_full_report(dataclasses.replace(full_results(), noise_stress=None))
    with pytest.raises(InvalidInputError):
        render_full_report(dataclasses.replace(full_results(), subset=True))


def test_subset_report_needs_a_subset() -> None:
    with pytest.raises(InvalidInputError, match="needs the results of a subset"):
        render_subset_report(full_results())
