#pragma once

// Identity of the library (architecture-m2.md 14.15): the version of the milestone register and
// the SHA-256 of the library's own code. The definition is generated by CMake at build time.

namespace sinus::dsp {

struct LibraryIdentity {
  const char* version;
  const char* source_sha256;
};

[[nodiscard]] LibraryIdentity library_identity() noexcept;

}  // namespace sinus::dsp
