# Identity of the library (architecture-m2.md 14.15), run in script mode:
#   cmake -DLIBS_ROOT=<libs> -DITEM=sinus-dsp -DVERSION_FILE=<VERSION> -DOUTPUT=<file.cpp> -P SourceDigest.cmake
# Digest: SHA-256 of the manifest of every regular file under <ITEM>/include and <ITEM>/src with
# no path component starting with '.', named by its path relative to LIBS_ROOT, sorted in
# code-point order, CR LF replaced by LF, one line "<sha256>  <name>" per file. The output file
# is rewritten only when its content changes.
if(NOT DEFINED ITEM)
  set(ITEM "sinus-dsp")
endif()
file(STRINGS "${VERSION_FILE}" version_line LIMIT_COUNT 1)
string(STRIP "${version_line}" version_text)

set(names "")
foreach(dir include src)
  file(GLOB_RECURSE found RELATIVE "${LIBS_ROOT}" "${LIBS_ROOT}/${ITEM}/${dir}/*")
  foreach(name IN LISTS found)
    if(NOT name MATCHES "(^|/)\\." AND NOT IS_DIRECTORY "${LIBS_ROOT}/${name}")
      list(APPEND names "${name}")
    endif()
  endforeach()
endforeach()
list(SORT names COMPARE STRING CASE SENSITIVE)

set(manifest "")
foreach(name IN LISTS names)
  file(READ "${LIBS_ROOT}/${name}" content)
  string(REPLACE "\r\n" "\n" content "${content}")
  string(SHA256 file_digest "${content}")
  string(APPEND manifest "${file_digest}  ${name}\n")
endforeach()
string(SHA256 digest "${manifest}")

set(text "// Generated by cmake/SourceDigest.cmake. Do not edit.
#include \"sinus/dsp/version.hpp\"

namespace sinus::dsp {

LibraryIdentity library_identity() noexcept {
  return LibraryIdentity{\"${version_text}\", \"${digest}\"};
}

}  // namespace sinus::dsp
")
set(old "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" old)
endif()
if(NOT old STREQUAL text)
  get_filename_component(out_dir "${OUTPUT}" DIRECTORY)
  file(MAKE_DIRECTORY "${out_dir}")
  file(WRITE "${OUTPUT}" "${text}")
endif()
