"""Requirement tests of SRS-009: reproducible validation report (RC-004).

SRS-009: a single command runs QRS detection and the evaluation of SRS-008 and SRS-011 on
the reference database and writes the report of SRS-012 to `docs/validation/`; two runs on
the same inputs and software version produce byte-identical reports.

The reports are generated from the fixture databases of `conftest.py` (records written with
wfdb, RECORDS files, checksum lists, `Database` values pinned to the fixture lists), without
network:
- in the test process, with the detector double of `conftest.py`;
- in separate Python processes, from other folders, with other hash seeds and text
  encodings, to show that nothing in the report depends on the process or the machine;
- through the command itself (`scripts/validate.py`), with the real detector on noise-free
  synthetic ECGs, from a copy of the scripts folder laid out as in the repository. The
  command uses the pinned checksum lists of the software; for these runs only, a driver
  process sets them to the digests of the fixture lists before running the script.
"""

from __future__ import annotations

import codecs
import os
import re
import shutil
import socket
import subprocess
import sys
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import pytest

from sinus_dsp.data.physionet import Database
from sinus_dsp.evaluation.report import render_full_report
from sinus_dsp.evaluation.run import run_validation, write_validation_report

pytestmark = pytest.mark.usefixtures("forbid_network")

MITDB_TITLE = "MIT-BIH Arrhythmia Database"
NSTDB_TITLE = "MIT-BIH Noise Stress Test Database"
GENERATED_BY = "Generated by dsp/scripts/validate.py; do not edit by hand."
SCRIPTS_DIR = Path(__file__).resolve().parents[2] / "scripts"

# A script run in separate Python processes: it writes the report of fixture databases with
# a detector double (the samples above 0.5 mV), without network access.
REPORT_DRIVER = '''\
"""Write the validation report of fixture databases with a detector double, without network.

Usage: python <this file> OUTPUT DATA_ROOT MITDB_PIN NSTDB_PIN
"""

import socket
import sys
import urllib.request
from pathlib import Path

import numpy as np


def _refuse(*args, **kwargs):
    raise RuntimeError("network access attempted in a test without network")


socket.socket.connect = _refuse
socket.create_connection = _refuse
socket.getaddrinfo = _refuse
urllib.request.urlopen = _refuse

from sinus_dsp.data.physionet import Database  # noqa: E402
from sinus_dsp.evaluation.run import write_validation_report  # noqa: E402


def spike_detector(signal_mv, fs_hz, mains_hz):
    return np.flatnonzero(np.asarray(signal_mv, dtype=np.float64) > 0.5).astype(np.int64)


output, data_root, mitdb_pin, nstdb_pin = sys.argv[1:5]
write_validation_report(
    Path(output),
    Path(data_root),
    mitdb=Database(
        slug="mitdb",
        version="1.0.0",
        title="MIT-BIH Arrhythmia Database",
        checksum_list_sha256=mitdb_pin,
    ),
    nstdb=Database(
        slug="nstdb",
        version="1.0.0",
        title="MIT-BIH Noise Stress Test Database",
        checksum_list_sha256=nstdb_pin,
    ),
    detector=spike_detector,
    fetch=None,
)
'''


def _databases(fixture: Any) -> tuple[Database, Database]:
    """The two `Database` values of a fixture, pinned to the digests of its checksum lists."""
    mitdb = Database(
        slug="mitdb",
        version="1.0.0",
        title=MITDB_TITLE,
        checksum_list_sha256=fixture.mitdb.checksum_list_sha256,
    )
    nstdb = Database(
        slug="nstdb",
        version="1.0.0",
        title=NSTDB_TITLE,
        checksum_list_sha256=fixture.nstdb.checksum_list_sha256,
    )
    return mitdb, nstdb


def _write_report(
    fixture: Any, output: Path, detector: Any, fetch: Any = None, data_root: Path | None = None
) -> bytes:
    """Write the report of ``fixture`` to ``output`` and return its bytes."""
    mitdb, nstdb = _databases(fixture)
    write_validation_report(
        output,
        data_root if data_root is not None else fixture.data_root,
        mitdb=mitdb,
        nstdb=nstdb,
        detector=detector,
        fetch=fetch,
    )
    return output.read_bytes()


@dataclass(frozen=True)
class Reference:
    """The report of the standard fixture written in the test process, and where."""

    data: bytes
    output: Path
    data_root: Path


@pytest.fixture(scope="module")
def reference(
    evaluation_fixture: Any,
    make_spike_detector: Callable[[], Any],
    network_forbidden: Callable[[], Any],
    tmp_path_factory: pytest.TempPathFactory,
) -> Reference:
    """The report of the standard fixture, written once in the test process."""
    output = tmp_path_factory.mktemp("srs009-reference") / "qrs-ec57-report.md"
    with network_forbidden():
        data = _write_report(evaluation_fixture, output, make_spike_detector())
    return Reference(data=data, output=output, data_root=evaluation_fixture.data_root)


def _python(
    arguments: Sequence[str], cwd: Path, env: Mapping[str, str] | None = None
) -> subprocess.CompletedProcess[str]:
    """Run ``python <arguments>`` in a separate process, with the test environment."""
    return subprocess.run(
        [sys.executable, *arguments],
        cwd=cwd,
        env={**os.environ, **(env or {})},
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        timeout=600,
        check=False,
    )


# --------------------------------------------------------------------------------------------
# Byte-identical reports
# --------------------------------------------------------------------------------------------


@pytest.mark.requirement("SRS-009")
def test_report_generated_twice_from_fixture_records_is_byte_identical(
    tmp_path: Path,
    evaluation_fixture: Any,
    make_spike_detector: Callable[[], Any],
    reference: Reference,
) -> None:
    """The verification case of SRS-009: two runs on the same inputs.

    Input: the standard fixture databases (14 MIT-BIH and 12 noise stress records), the
    report generated twice into two new folders, each run with its own detector double.
    Expected: the two reports are byte-identical, and identical to the report generated
    earlier in the same process; each output folder holds only the report.
    """
    first_folder, second_folder = tmp_path / "first", tmp_path / "second"
    first_folder.mkdir()
    second_folder.mkdir()

    first = _write_report(evaluation_fixture, first_folder / "report.md", make_spike_detector())
    second = _write_report(evaluation_fixture, second_folder / "report.md", make_spike_detector())

    assert first == second
    assert first == reference.data
    assert [p.name for p in first_folder.iterdir()] == ["report.md"]
    assert [p.name for p in second_folder.iterdir()] == ["report.md"]


@pytest.mark.requirement("SRS-009")
def test_report_written_is_the_rendered_report_in_utf8(
    evaluation_fixture: Any, make_spike_detector: Callable[[], Any], reference: Reference
) -> None:
    """The file written is the report rendered from the evaluation results, in UTF-8.

    Input: the evaluation of the standard fixture, run again, and its full report rendered.
    Expected: the file written for the same inputs holds exactly the UTF-8 encoding of the
    rendered text (no other line ending, no byte-order mark).
    """
    mitdb, nstdb = _databases(evaluation_fixture)
    results = run_validation(
        evaluation_fixture.data_root,
        mitdb=mitdb,
        nstdb=nstdb,
        detector=make_spike_detector(),
        fetch=None,
    )

    assert render_full_report(results).encode("utf-8") == reference.data


@pytest.mark.requirement("SRS-009")
def test_report_depends_on_no_date_time_host_user_or_path(reference: Reference) -> None:
    """The report is plain text that depends only on the data, the software and the settings.

    Input: the report of the standard fixture.
    Expected: valid UTF-8 without a byte-order mark; line feeds only (no carriage return);
    one line feed at the end and no empty line after it; no trailing spaces; neither the
    data folder, nor the output folder, nor the home folder, nor the host name; no date
    (YYYY-MM-DD) and no time of day (hh:mm:ss).
    """
    data = reference.data
    text = data.decode("utf-8")

    assert not data.startswith(codecs.BOM_UTF8)
    assert b"\r" not in data
    assert data.endswith(b"\n") and not data.endswith(b"\n\n")
    assert [line for line in text.split("\n") if line != line.rstrip()] == []
    for folder in (reference.data_root, reference.output.parent, Path.home()):
        assert str(folder) not in text
        assert folder.as_posix() not in text
    host = socket.gethostname()
    if len(host) >= 3:
        assert not re.search(rf"\b{re.escape(host)}\b", text, re.IGNORECASE)
    assert not re.search(r"\b\d{4}-\d{2}-\d{2}\b", text)
    assert not re.search(r"\b\d{1,2}:\d{2}:\d{2}\b", text)


@pytest.mark.requirement("SRS-009")
def test_report_is_identical_from_other_folders_and_processes(
    tmp_path: Path,
    evaluation_fixture: Any,
    copy_evaluation_fixture: Callable[[Any, Path], Any],
    reference: Reference,
) -> None:
    """Two runs of the same inputs on the same software, in other conditions.

    Input: the standard fixture copied to two other data folders (one with a space in its
    path); the report written by two separate Python processes, each started in another
    working folder, with the hash seeds 0 and 4242 and the UTF-8 mode of Python on and off.
    Expected: both reports are byte-identical, and identical to the report written in the
    test process from the original folder.
    """
    driver = tmp_path / "write_report.py"
    driver.write_text(REPORT_DRIVER, encoding="utf-8")
    pins = [evaluation_fixture.mitdb.checksum_list_sha256]
    pins.append(evaluation_fixture.nstdb.checksum_list_sha256)
    runs = [
        ("first", "data", {"PYTHONHASHSEED": "0", "PYTHONUTF8": "1"}),
        ("second run", "data copy", {"PYTHONHASHSEED": "4242", "PYTHONUTF8": "0"}),
    ]
    reports = []
    for folder_name, data_name, env in runs:
        folder = tmp_path / folder_name
        (folder / "work").mkdir(parents=True)
        (folder / "out").mkdir()
        fixture = copy_evaluation_fixture(evaluation_fixture, folder / data_name)
        output = folder / "out" / "qrs-ec57-report.md"
        arguments = [str(driver), str(output), str(fixture.data_root), *pins]

        completed = _python(arguments, cwd=folder / "work", env=env)

        assert completed.returncode == 0, completed.stderr
        reports.append(output.read_bytes())

    assert reports[0] == reports[1]
    assert reports[0] == reference.data


@pytest.mark.requirement("SRS-009")
def test_report_is_identical_when_missing_files_are_downloaded(
    tmp_path: Path,
    evaluation_fixture: Any,
    copy_evaluation_fixture: Callable[[Any, Path], Any],
    make_spike_detector: Callable[[], Any],
    make_fake_fetch: Callable[[dict[str, bytes]], Any],
    reference: Reference,
) -> None:
    """The same report whether the data was already present or obtained by the run.

    Input: a copy of the standard fixture without the MIT-BIH files 101.dat and 118.atr and
    the noise stress file 119e06.hea; a fetch function that serves exactly these three files
    at their PhysioNet addresses (https://physionet.org/files/<database>/1.0.0/<file>).
    Expected: the report is written, byte-identical to the report of the complete local
    copy; each of the three files was asked for and is now present.
    """
    fixture = copy_evaluation_fixture(evaluation_fixture, tmp_path / "data")
    served = {}
    for database, name in ((fixture.mitdb, "101.dat"), (fixture.mitdb, "118.atr")) + (
        (fixture.nstdb, "119e06.hea"),
    ):
        (database.folder.folder / name).unlink()
        url = f"https://physionet.org/files/{database.slug}/1.0.0/{name}"
        served[url] = database.folder.files[name]
    fetch = make_fake_fetch(served)
    output = tmp_path / "out" / "qrs-ec57-report.md"
    output.parent.mkdir()

    data = _write_report(fixture, output, make_spike_detector(), fetch=fetch)

    assert data == reference.data
    assert set(served) <= set(fetch.calls)
    assert (fixture.mitdb.folder.folder / "101.dat").read_bytes() == served[
        "https://physionet.org/files/mitdb/1.0.0/101.dat"
    ]


@pytest.mark.requirement("SRS-009")
def test_report_states_how_it_is_regenerated(
    reference: Reference, parse_report: Callable[[str], Any]
) -> None:
    """The report says which command regenerates it.

    Input: the report of the standard fixture.
    Expected: the line "Generated by dsp/scripts/validate.py; do not edit by hand." before
    the first section of results.
    """
    report = parse_report(reference.data.decode("utf-8"))
    lines = list(report.lines)

    assert GENERATED_BY in lines
    first_section = min(i for i, level, _ in report.headings if level > 1)
    assert lines.index(GENERATED_BY) < first_section


# --------------------------------------------------------------------------------------------
# The single command
# --------------------------------------------------------------------------------------------


@pytest.mark.requirement("SRS-009")
def test_single_command_runs_detection_and_writes_the_report_to_docs_validation(
    tmp_path: Path,
    ecg_evaluation_fixture: Any,
    write_command_driver: Callable[[Path], Path],
    parse_report: Callable[[str], Any],
) -> None:
    """The command `validate.py`, with its default output, run twice.

    Input: a copy of the scripts folder of the software in `<repo>/dsp/scripts/`, with an
    existing `<repo>/docs/validation/` folder, as in the repository; the fixture databases of
    6-min noise-free synthetic ECGs (MIT-BIH records 118 at 75 bpm and 119 at 60 bpm, the 12
    noise stress records); the pinned checksum lists set to the fixture lists for these runs
    only. First run: `validate.py --offline --data-dir <fixture>` from `<repo>`; second run:
    the same with `--output <another path>`, from another folder.
    Expected: both runs exit with status 0; the first writes
    `<repo>/docs/validation/qrs-ec57-report.md` and nothing else in that folder; the second
    report is byte-identical to the first. The report comes from the real detector: every
    record has all its reference beats from 5:00 as TP, FN 0, FP 0, Se and +P 100.00, and
    both databases are stated as verified.
    """
    fixture = ecg_evaluation_fixture
    repo = tmp_path / "repo"
    shutil.copytree(
        SCRIPTS_DIR, repo / "dsp" / "scripts", ignore=shutil.ignore_patterns("__pycache__")
    )
    validation = repo / "docs" / "validation"
    validation.mkdir(parents=True)
    script = repo / "dsp" / "scripts" / "validate.py"
    driver = write_command_driver(tmp_path)
    pins = [fixture.mitdb.checksum_list_sha256, fixture.nstdb.checksum_list_sha256]
    options = ["--offline", "--data-dir", str(fixture.data_root)]
    elsewhere = tmp_path / "elsewhere"
    elsewhere.mkdir()
    other_output = elsewhere / "report.md"

    first = _python([str(driver), *pins, str(script), *options], cwd=repo)
    second = _python(
        [str(driver), *pins, str(script), *options, "--output", str(other_output)],
        cwd=elsewhere,
    )

    assert first.returncode == 0, first.stderr
    assert second.returncode == 0, second.stderr
    assert [p.name for p in validation.iterdir()] == ["qrs-ec57-report.md"]
    data = (validation / "qrs-ec57-report.md").read_bytes()
    assert other_output.read_bytes() == data
    report = parse_report(data.decode("utf-8"))
    per_record = report.section("results per record").table_with_row("118")
    for name, record in fixture.mitdb.records.items():
        assert per_record.row(name)[2:] == (str(record.tp), "0", "0", "100.00", "100.00")
    noise = report.section("noise stress").table_with_row("118e24")
    for name, record in fixture.nstdb.records.items():
        assert noise.row(name)[2:] == (str(record.tp), "0", "0", "100.00", "100.00")
    for database in (fixture.mitdb, fixture.nstdb):
        assert f"verified: {database.n_listed_files} files match" in report.text
        assert database.checksum_list_sha256 in report.text
