"""Requirement tests of SRS-016: content of the subset report (RC-004).

SRS-016 (v0.7.2): the subset report shall contain the items of SRS-012 for records 100, 105,
108, 119, 203 and 207, with the outcome of the verification of their files in place of the
outcome of the SRS-001 verification and without the pass or fail of the SRS-007 thresholds,
and shall state that it covers a subset of records for regression checking and is not the
performance evaluation of SRS-007. The check runs QRS detection with the settings of SRS-007
and the evaluation of SRS-008 and SRS-011 on these records.

The report tested is the one that the check regenerates (`check_subset_report` with a path
for the regenerated report) from fixture databases whose records are named as the subset
(`conftest.py`): channel 0 of each record is flat except for 1 mV spikes, the detector double
returns the spike samples, so every count is known (worked out in the docstring of
`_subset_spike_records`). Record 207 has two ventricular flutter episodes, one that ends before
5:00 and one after it. A record 101 outside the subset is written and listed in `RECORDS`.

The items of SRS-012 and their tests:
- per-record and aggregate statistics of SRS-011:
  - `test_report_gives_the_statistics_of_each_subset_record`,
  - `test_report_gives_the_gross_and_average_statistics`;
- the five lowest Se and +P among the defined values, ties by record name:
  - `test_report_ranks_the_lowest_values`,
  - `test_ranking_lists_only_defined_values`;
- (the pass or fail of the thresholds is excepted):
  - `test_report_states_no_threshold_outcome`;
- the database name and version and the outcome of its verification:
  - `test_report_states_the_database_and_the_verification_of_the_six_records`,
  - `test_report_states_the_database_that_was_verified`;
- the licence under which the database is published, with the address of the licence text
  (SRS-012 v0.7.2), in the row `Database licence` right after the row `Database` (the form of
  architecture sections 8.10, 8.11 and 8.15), from the `Database` verified, and the Open Data
  Commons Attribution License v1.0 for version 1.0.0:
  - `test_report_states_the_licence_of_the_database`,
  - `test_report_states_the_database_that_was_verified`,
  - `test_report_states_the_licence_of_version_1_0_0_of_the_database`;
- the software version with the identifier of the source code, checked as for SRS-012 (the
  test computes the identifier itself, architecture 8.14), and the settings used:
  - `test_report_states_the_software_identity`,
  - `test_report_states_the_settings_of_srs_007`;
- the versions of the third-party software at run time:
  - `test_report_states_the_software_identity`;
- what was not scored because of ventricular flutter or fibrillation episodes:
  - `test_report_states_what_was_not_scored`,
  - `test_report_says_so_when_no_record_has_an_episode`;
- the statement on what the results mean:
  - `test_report_states_that_it_is_a_technical_evaluation_only`.

The statement on the subset for regression checking:
- `test_report_states_that_it_is_a_subset_for_regression_checking`.

The headings, sentences, table columns and row labels are the documented report format
(architecture, sections 8.10 and 8.11), which is normative for the stored subset report, so
the tests compare them literally.
"""

from __future__ import annotations

import re
from collections.abc import Callable, Sequence
from dataclasses import dataclass, replace
from pathlib import Path
from typing import Any

import pytest

from sinus_dsp.data.physionet import MITDB, ODC_BY_1_0, Database, DatabaseLicence
from sinus_dsp.errors import SubsetReportMismatchError
from sinus_dsp.evaluation.metrics import RecordCounts
from sinus_dsp.evaluation.report import render_subset_report
from sinus_dsp.evaluation.run import EvaluationSettings
from sinus_dsp.evaluation.subset import check_subset_report, run_subset

pytestmark = pytest.mark.usefixtures("forbid_network")

STATEMENT = (
    "Technical evaluation only. Sinus is not a medical device; these results are not a "
    "clinical validation."
)
MITDB_TITLE = "MIT-BIH Arrhythmia Database"
TITLE = "# QRS detection: EC57 subset report for regression checking"
SUBSET_PARAGRAPH = (
    "This report covers records 100, 105, 108, 119, 203 and 207 of the {title}. It is a "
    "regression check run on every change, not the performance evaluation against the "
    "targets, which uses all 48 records (qrs-ec57-report.md)."
)
ORIGIN = "Generated by dsp/scripts/subset_check.py; do not edit by hand."
NOT_SCORED_SENTENCE = (
    "The first 5 min of each record are not scored. Ventricular flutter and fibrillation "
    "episodes are not scored either. The durations and counts below cover the part of each "
    "record from 5:00 to its end, except the episodes in the record, which are counted over "
    "the whole record."
)
NO_EPISODE_SENTENCE = (
    "No ventricular flutter or fibrillation episode is annotated in these records."
)
FLUTTER_SENTENCE = (
    "Flutter-wave annotations outside ventricular flutter and fibrillation episodes, "
    "in all records: {n}."
)
MATCHING = (
    "EC57 beat by beat, pairing rules of the WFDB comparator bxb; match window 150 ms; first "
    "5 min of each record not scored; ventricular flutter and fibrillation episodes not scored"
)
SECTIONS = (
    "Software, data and settings",
    "Results per record",
    "Lowest sensitivity",
    "Lowest positive predictivity",
    "Segments not scored",
)
SUBSET = ("100", "105", "108", "119", "203", "207")


def _database(
    fixture: Any,
    *,
    title: str = MITDB_TITLE,
    version: str = "1.0.0",
    licence: DatabaseLicence | None = None,
) -> Database:
    """The `Database` of a fixture, pinned to its checksum list, with the fixture licence
    (`FIXTURE_LICENCES` of `conftest.py`) unless another licence is given."""
    return Database(
        slug="mitdb",
        version=version,
        title=title,
        checksum_list_sha256=fixture.checksum_list_sha256,
        licence=fixture.licence if licence is None else licence,
    )


@dataclass(frozen=True)
class Regenerated:
    """A subset report regenerated by the check, and the evaluation it comes from."""

    text: str
    data: bytes
    results: Any
    calls: tuple[tuple[int, float, int], ...]


def _regenerate(
    fixture: Any,
    folder: Path,
    detector_class: Callable[[], Any],
    *,
    database: Database | None = None,
) -> Regenerated:
    """Run the check on ``fixture`` against an absent stored report (one difference), read
    the report it regenerated, and run the evaluation of the check once more."""
    database = database or _database(fixture)
    detector = detector_class()
    with pytest.raises(SubsetReportMismatchError):
        check_subset_report(
            folder / "absent.md",
            fixture.data_root,
            regenerated_path=folder / "regenerated.md",
            database=database,
            detector=detector,
            fetch=None,
        )
    data = (folder / "regenerated.md").read_bytes()
    results = run_subset(
        fixture.data_root, database=database, detector=detector_class(), fetch=None
    )
    return Regenerated(
        text=data.decode("utf-8"), data=data, results=results, calls=tuple(detector.calls)
    )


@pytest.fixture(scope="module")
def regenerated(
    subset_fixture: Any,
    make_spike_detector: Callable[[], Any],
    network_forbidden: Callable[[], Any],
    tmp_path_factory: pytest.TempPathFactory,
) -> Regenerated:
    """The subset report regenerated from the spike subset fixture."""
    folder = tmp_path_factory.mktemp("srs016-content")
    with network_forbidden():
        return _regenerate(subset_fixture, folder, make_spike_detector)


def _lines_starting_with(text: str, prefix: str) -> list[str]:
    return [line for line in text.split("\n") if line.startswith(prefix)]


def _paragraphs(text: str) -> list[str]:
    """The blocks of the report that are neither headings nor tables."""
    blocks = [block for block in text.split("\n\n") if block.strip()]
    return [b.strip("\n") for b in blocks if not b.startswith("#") and not b.startswith("|")]


# --------------------------------------------------------------------------------------------
# Statements: what the results mean, and the subset for regression checking
# --------------------------------------------------------------------------------------------


@pytest.mark.requirement("SRS-016")
def test_report_states_that_it_is_a_technical_evaluation_only(
    regenerated: Regenerated, parse_report: Callable[[str], Any]
) -> None:
    """The statement of SRS-012 on what the results do not mean, in the subset report.

    Input: the subset report regenerated from the spike subset fixture.
    Expected: "Technical evaluation only. Sinus is not a medical device; these results are
    not a clinical validation." verbatim, as a paragraph of its own, before the first
    section.
    """
    report = parse_report(regenerated.text)
    lines = list(report.lines)

    assert STATEMENT in lines
    index = lines.index(STATEMENT)
    assert lines[index - 1] == "" and lines[index + 1] == ""
    assert index < min(i for i, level, _ in report.headings if level > 1)


@pytest.mark.requirement("SRS-016")
def test_report_states_that_it_is_a_subset_for_regression_checking(
    regenerated: Regenerated, parse_report: Callable[[str], Any]
) -> None:
    """The report states that it covers a subset for regression checking and is not the
    performance evaluation of SRS-007.

    Input: the subset report regenerated from the spike subset fixture.
    Expected: the first line is the title "# QRS detection: EC57 subset report for regression
    checking"; then, as paragraphs before the first section, in this order: the statement on
    what the results mean, "This report covers records 100, 105, 108, 119, 203 and 207 of the
    MIT-BIH Arrhythmia Database. It is a regression check run on every change, not the
    performance evaluation against the targets, which uses all 48 records
    (qrs-ec57-report.md).", and "Generated by dsp/scripts/subset_check.py; do not edit by
    hand." (architecture, section 8.11).
    """
    report = parse_report(regenerated.text)
    first_section = min(i for i, level, _ in report.headings if level > 1)
    paragraphs = _paragraphs("\n".join(report.lines[:first_section]))

    assert report.lines[0] == TITLE
    assert paragraphs == [STATEMENT, SUBSET_PARAGRAPH.format(title=MITDB_TITLE), ORIGIN]


@pytest.mark.requirement("SRS-016")
def test_report_has_the_documented_sections_and_text_form(
    regenerated: Regenerated, parse_report: Callable[[str], Any], subset_fixture: Any
) -> None:
    """The layout of the subset report (architecture, sections 8.10 and 8.11).

    Input: the subset report regenerated from the spike subset fixture.
    Expected: the headings are the title and the sections "Software, data and settings",
    "Results per record", "Lowest sensitivity", "Lowest positive predictivity" and
    "Segments not scored", in this order, and no other; the text is UTF-8 with line feeds
    only, one line feed at the end, no trailing spaces, blocks separated by exactly one
    empty line, and it does not contain the path of the data folder (the stored report must
    be equal on every machine).
    """
    report = parse_report(regenerated.text)
    data = regenerated.data

    assert [(level, title) for _, level, title in report.headings] == [
        (1, TITLE.removeprefix("# ")),
        *((2, title) for title in SECTIONS),
    ]
    assert b"\r" not in data
    assert data.endswith(b"\n") and not data.endswith(b"\n\n")
    assert not any(line != line.rstrip() for line in regenerated.text.split("\n"))
    assert "\n\n\n" not in regenerated.text
    for text in (str(subset_fixture.data_root), subset_fixture.data_root.as_posix()):
        assert text not in regenerated.text


@pytest.mark.requirement("SRS-016")
def test_report_written_by_the_check_is_the_rendered_subset_report(
    regenerated: Regenerated,
) -> None:
    """The file that the check writes is the subset report of the evaluation it ran.

    Input: the report regenerated from the spike subset fixture, and the results of
    `run_subset` on the same fixture rendered with `render_subset_report`.
    Expected: the results cover a subset (`subset` true) and hold no noise stress test; the
    report written is the UTF-8 encoding of the rendered text.
    """
    assert regenerated.results.subset is True
    assert regenerated.results.noise_stress is None
    assert render_subset_report(regenerated.results).encode("utf-8") == regenerated.data


@pytest.mark.requirement("SRS-016")
def test_regenerated_report_does_not_depend_on_the_run_or_the_folder(
    tmp_path: Path,
    regenerated: Regenerated,
    subset_fixture: Any,
    copy_subset_fixture: Callable[..., Any],
    make_spike_detector: Callable[[], Any],
) -> None:
    """The report compared with the stored one is the same for every run on the same data.

    Input: the spike subset fixture, regenerated again; and a copy of it in another folder
    whose path holds a space and non-ASCII characters.
    Expected: both reports are byte-identical to the report regenerated earlier.
    """
    again = _regenerate(subset_fixture, _folder(tmp_path / "a"), make_spike_detector)
    copy = copy_subset_fixture(subset_fixture, tmp_path / "copie des données" / "data")
    moved = _regenerate(copy, _folder(tmp_path / "b"), make_spike_detector)

    assert again.data == regenerated.data
    assert moved.data == regenerated.data


def _folder(path: Path) -> Path:
    path.mkdir(parents=True)
    return path


# --------------------------------------------------------------------------------------------
# Statistics of SRS-011 for the six records
# --------------------------------------------------------------------------------------------


def _expected_row(record: Any, percent_text: Callable[[int, int], str]) -> tuple[str, ...]:
    return (
        record.name,
        record.signal_names[0],
        str(record.tp),
        str(record.fn),
        str(record.fp),
        percent_text(record.tp, record.tp + record.fn),
        percent_text(record.tp, record.tp + record.fp),
    )


@pytest.mark.requirement("SRS-016")
def test_report_gives_the_statistics_of_each_subset_record(
    regenerated: Regenerated,
    subset_fixture: Any,
    parse_report: Callable[[str], Any],
    percent_text: Callable[[int, int], str],
) -> None:
    """The per-record statistics of SRS-011, for the six records and only them.

    Input: the subset report regenerated from the spike subset fixture, whose `RECORDS` file
    and folder also hold record 101.
    Expected: the table of "Results per record" (columns Record, Signal, TP, FN, FP, Se (%),
    +P (%)) has one row per subset record in increasing order of name, then "Gross" and
    "Average", and no row for record 101; each record row has the designed values: 100 MLII
    119 1 0 99.17 100.00; 105 MLII 118 2 5 98.33 95.93; 108 V5 130 4 9 97.01 93.53; 119 MLII
    134 0 0 100.00 100.00; 203 MLII 117 3 2 97.50 98.32; 207 MLII 95 0 0 100.00 100.00.
    """
    table = parse_report(regenerated.text).section("results per record").table_with_row("100")

    assert table.header == ("Record", "Signal", "TP", "FN", "FP", "Se (%)", "+P (%)")
    assert table.first_cells() == [*SUBSET, "Gross", "Average"]
    for record in subset_fixture.subset_records():
        assert table.row(record.name) == _expected_row(record, percent_text), record.name
    assert [table.row(name)[1:] for name in SUBSET] == [
        ("MLII", "119", "1", "0", "99.17", "100.00"),
        ("MLII", "118", "2", "5", "98.33", "95.93"),
        ("V5", "130", "4", "9", "97.01", "93.53"),
        ("MLII", "134", "0", "0", "100.00", "100.00"),
        ("MLII", "117", "3", "2", "97.50", "98.32"),
        ("MLII", "95", "0", "0", "100.00", "100.00"),
    ]


@pytest.mark.requirement("SRS-016")
def test_report_gives_the_gross_and_average_statistics(
    regenerated: Regenerated,
    subset_fixture: Any,
    parse_report: Callable[[str], Any],
    percent_text: Callable[[int, int], str],
    mean_percent_text: Callable[[Sequence[tuple[int, int]]], str],
) -> None:
    """The aggregate statistics of SRS-011 over the six records.

    Input: the subset report regenerated from the spike subset fixture: summed TP 713, FN 10,
    FP 16; Se and +P defined for all six records.
    Expected: the row "Gross" has the empty signal cell, 713, 10, 16, 98.62 and 97.81 (from
    the summed counts); the row "Average" has 98.67 and 97.96 (means of the six per-record
    values); the paragraph "The averages are the means of the defined per-record values: Se
    is defined for 6 of 6 records, +P for 6 of 6 records."
    """
    section = parse_report(regenerated.text).section("results per record")
    table = section.table_with_row("100")
    records = subset_fixture.subset_records()
    tp, fn, fp = (sum(getattr(r, key) for r in records) for key in ("tp", "fn", "fp"))
    se = mean_percent_text([(r.tp, r.tp + r.fn) for r in records])
    ppv = mean_percent_text([(r.tp, r.tp + r.fp) for r in records])

    assert (tp, fn, fp) == (713, 10, 16)
    assert (percent_text(tp, tp + fn), percent_text(tp, tp + fp), se, ppv) == (
        "98.62",
        "97.81",
        "98.67",
        "97.96",
    )
    assert table.row("Gross") == ("Gross", "", "713", "10", "16", "98.62", "97.81")
    assert table.row("Average") == ("Average", "", "", "", "", "98.67", "97.96")
    assert (
        "The averages are the means of the defined per-record values: Se is defined for 6 of "
        "6 records, +P for 6 of 6 records."
    ) in section.lines


def _ranking(report: Any, keyword: str) -> list[tuple[str, ...]]:
    tables = report.section(keyword).tables()
    assert len(tables) == 1, f"{len(tables)} tables in {keyword!r}"
    return [tuple(row) for row in tables[0].rows]


@pytest.mark.requirement("SRS-016")
def test_report_ranks_the_lowest_values(
    regenerated: Regenerated, parse_report: Callable[[str], Any]
) -> None:
    """The five records with the lowest Se and with the lowest +P, ties ordered by name.

    Input: the subset report regenerated from the spike subset fixture. Se: 97.01 (108),
    97.50 (203), 98.33 (105), 99.17 (100), then 100.00 for 119 and 207 (a tie at the fifth
    place). +P: 93.53 (108), 95.93 (105), 98.32 (203), then 100.00 for 100, 119 and 207.
    Expected: "Lowest sensitivity": 1 108 97.01, 2 203 97.50, 3 105 98.33, 4 100 99.17,
    5 119 100.00 (207 not listed). "Lowest positive predictivity": 1 108 93.53, 2 105 95.93,
    3 203 98.32, 4 100 100.00, 5 119 100.00 (207 not listed). Each section has the
    documented sentence before its table.
    """
    report = parse_report(regenerated.text)

    assert _ranking(report, "lowest sensitivity") == [
        ("1", "108", "97.01"),
        ("2", "203", "97.50"),
        ("3", "105", "98.33"),
        ("4", "100", "99.17"),
        ("5", "119", "100.00"),
    ]
    assert _ranking(report, "lowest positive predictivity") == [
        ("1", "108", "93.53"),
        ("2", "105", "95.93"),
        ("3", "203", "98.32"),
        ("4", "100", "100.00"),
        ("5", "119", "100.00"),
    ]
    for measure, keyword in (("Se", "lowest sensitivity"), ("+P", "lowest positive")):
        assert (
            f"The records with the lowest defined {measure}, at most 5, lowest first; ties are "
            "ordered by record name."
        ) in report.section(keyword).lines


@pytest.mark.requirement("SRS-016")
def test_ranking_lists_only_defined_values(
    regenerated: Regenerated, parse_report: Callable[[str], Any]
) -> None:
    """Fewer than five defined values: only those records are ranked (SRS-012).

    Input: the results of the spike subset fixture with the counts of records 100, 105, 108
    and 119 replaced by TP 0, FN 0, FP 0 (Se and +P not defined) and of record 203 by TP 0,
    FN 4, FP 0 (Se 0.00, +P not defined), rendered as the subset report.
    Expected: "Lowest sensitivity" ranks 1 203 0.00 and 2 207 100.00 only; "Lowest positive
    predictivity" ranks 1 207 100.00 only; the averages paragraph says Se is defined for 2
    of 6 records and +P for 1 of 6.
    """
    counts = {
        name: RecordCounts(record=name, tp=0, fn=0, fp=0) for name in ("100", "105", "108", "119")
    }
    counts["203"] = RecordCounts(record="203", tp=0, fn=4, fp=0)
    records = tuple(
        replace(ev, counts=counts[ev.record]) if ev.record in counts else ev
        for ev in regenerated.results.records
    )
    report = parse_report(render_subset_report(replace(regenerated.results, records=records)))

    assert _ranking(report, "lowest sensitivity") == [("1", "203", "0.00"), ("2", "207", "100.00")]
    assert _ranking(report, "lowest positive predictivity") == [("1", "207", "100.00")]
    assert (
        "The averages are the means of the defined per-record values: Se is defined for 2 of "
        "6 records, +P for 1 of 6 records."
    ) in report.section("results per record").lines


@pytest.mark.requirement("SRS-016")
def test_report_states_no_threshold_outcome(regenerated: Regenerated) -> None:
    """The pass or fail of the SRS-007 thresholds is not part of the subset report.

    Input: the subset report regenerated from the spike subset fixture (gross Se 98.62 and
    +P 97.81, both below the 99.50 % target).
    Expected: no section "Performance targets" and no section "Noise stress test"; no line
    states a target ("Target", "≥ 99.50", "99.50"), a "pass" or a "fail".
    """
    text = regenerated.text

    assert "Performance targets" not in text
    assert "Noise stress" not in text
    assert "Target" not in text and "99.50" not in text and "≥" not in text
    assert not re.search(r"\b(pass|fail)\b", text, re.IGNORECASE)


# --------------------------------------------------------------------------------------------
# Database, verification, software identity and settings
# --------------------------------------------------------------------------------------------


def _item(report: Any, label: str) -> str:
    table = report.section("software, data and settings").table_with_row(label)
    assert table.header == ("Item", "Value")
    return str(table.row(label)[1])


@pytest.mark.requirement("SRS-016")
def test_report_states_the_database_and_the_verification_of_the_six_records(
    regenerated: Regenerated, subset_fixture: Any, parse_report: Callable[[str], Any]
) -> None:
    """The database name and version, and the outcome of the verification of its files.

    Input: the subset report regenerated from the spike subset fixture, whose checksum list
    names 36 files, 28 of them files of the six records (worked out by the test from the
    list: the `.atr`, `.dat`, `.hea` and `.xws` files of each record, `108.at_`, `119.at_`,
    `203.at-` and `203.at_`).
    Expected: the row "Database" is "MIT-BIH Arrhythmia Database, version 1.0.0"; the row
    "Verification" is "verified: 28 files match the published SHA-256 checksum list
    (SHA256SUMS.txt, SHA-256 <digest of the fixture list>); records 100, 105, 108, 119, 203,
    207" (architecture, section 8.3); the row "Records" is 6.
    """
    report = parse_report(regenerated.text)
    n = len(subset_fixture.subset_files)

    assert n == 28
    assert _item(report, "Database") == "MIT-BIH Arrhythmia Database, version 1.0.0"
    assert _item(report, "Verification") == (
        f"verified: {n} files match the published SHA-256 checksum list (SHA256SUMS.txt, "
        f"SHA-256 {subset_fixture.checksum_list_sha256}); records 100, 105, 108, 119, 203, 207"
    )
    assert _item(report, "Records") == "6"


@pytest.mark.requirement("SRS-016")
def test_report_states_the_database_that_was_verified(
    tmp_path: Path,
    subset_fixture: Any,
    make_spike_detector: Callable[[], Any],
    parse_report: Callable[[str], Any],
) -> None:
    """The database stated is the one verified and evaluated, not a fixed text.

    Input: the spike subset fixture, with the database described as "Fixture Arrhythmia
    Database", version "2.3.4", licence "Licence de données d’essai 2.0" with the address
    https://licences.example.org/essai/2-0/ (same files and pinned list).
    Expected: the row "Database" is "Fixture Arrhythmia Database, version 2.3.4"; the row
    "Database licence" is "Licence de données d’essai 2.0,
    https://licences.example.org/essai/2-0/"; the subset paragraph names "the Fixture
    Arrhythmia Database"; neither "MIT-BIH" nor the fixture licence of the other runs appears.
    """
    database = _database(
        subset_fixture,
        title="Fixture Arrhythmia Database",
        version="2.3.4",
        licence=DatabaseLicence(
            name="Licence de données d’essai 2.0", url="https://licences.example.org/essai/2-0/"
        ),
    )
    run = _regenerate(subset_fixture, tmp_path, make_spike_detector, database=database)
    report = parse_report(run.text)

    assert _item(report, "Database") == "Fixture Arrhythmia Database, version 2.3.4"
    assert _item(report, "Database licence") == (
        "Licence de données d’essai 2.0, https://licences.example.org/essai/2-0/"
    )
    assert SUBSET_PARAGRAPH.format(title="Fixture Arrhythmia Database") in report.lines
    assert "MIT-BIH" not in run.text
    assert MITDB_LICENCE_TEXT not in run.text


# The fixture licence of `conftest.py` (`FIXTURE_LICENCES["mitdb"]`) and the licence of
# version 1.0.0 of the MIT-BIH Arrhythmia Database, as the row must state them (architecture,
# sections 8.10, 8.11 and 8.15).
MITDB_LICENCE_TEXT = (
    "Fixture Arrhythmia Data Licence 1.2, https://licences.example.org/fixture-arrhythmia/1-2/"
)
ODC_BY_TEXT = (
    "Open Data Commons Attribution License v1.0, https://opendatacommons.org/licenses/by/1-0/"
)
SECTION_2_ROWS = [
    "Software",
    "Runtime",
    "Database",
    "Database licence",
    "Verification",
    "Records",
    "Signal",
    "Mains interference filter",
    "Matching",
]


@pytest.mark.requirement("SRS-016")
def test_report_states_the_licence_of_the_database(
    regenerated: Regenerated, parse_report: Callable[[str], Any]
) -> None:
    """The licence under which the database is published, with the address of its text: an
    item of SRS-012 (v0.7.2) that the subset report contains.

    Input: the subset report regenerated from the spike subset fixture, whose `Database`
    carries the fixture licence "Fixture Arrhythmia Data Licence 1.2", address
    https://licences.example.org/fixture-arrhythmia/1-2/.
    Expected: the table of the section "Software, data and settings" has the rows Software,
    Runtime, Database, Database licence, Verification, Records, Signal, Mains interference
    filter and Matching, in this order (section 2 of the full report, architecture 8.10 and
    8.11); the report has one licence line, `| Database licence | Fixture Arrhythmia Data
    Licence 1.2, https://licences.example.org/fixture-arrhythmia/1-2/ |`, and does not state
    the Open Data Commons licence of the real database (the row comes from the `Database`
    verified); the results carry that licence.
    """
    report = parse_report(regenerated.text)
    table = report.section("software, data and settings").table_with_row("Database licence")

    assert table.header == ("Item", "Value")
    assert table.first_cells() == SECTION_2_ROWS
    assert _item(report, "Database licence") == MITDB_LICENCE_TEXT
    assert _lines_starting_with(regenerated.text, "| Database licence |") == [
        f"| Database licence | {MITDB_LICENCE_TEXT} |"
    ]
    assert "Open Data Commons" not in regenerated.text
    assert regenerated.results.mitdb.database.licence == DatabaseLicence(
        name="Fixture Arrhythmia Data Licence 1.2",
        url="https://licences.example.org/fixture-arrhythmia/1-2/",
    )


@pytest.mark.requirement("SRS-016")
def test_report_states_the_licence_of_version_1_0_0_of_the_database(
    tmp_path: Path,
    subset_fixture: Any,
    make_spike_detector: Callable[[], Any],
    parse_report: Callable[[str], Any],
) -> None:
    """For version 1.0.0 of the MIT-BIH Arrhythmia Database, the subset report states the Open
    Data Commons Attribution License v1.0, as SRS-012 requires of the full report.

    Input: the database description of the software (`MITDB`, the default of the check), with
    only its pinned digest replaced by that of the fixture list (`dataclasses.replace`); the
    subset report regenerated from the spike subset fixture with it.
    Expected: `MITDB` carries `ODC_BY_1_0`; the report has the line `| Database | MIT-BIH
    Arrhythmia Database, version 1.0.0 |` followed by `| Database licence | Open Data Commons
    Attribution License v1.0, https://opendatacommons.org/licenses/by/1-0/ |` (architecture,
    section 8.11), its only licence line.
    """
    database = replace(MITDB, checksum_list_sha256=subset_fixture.checksum_list_sha256)
    run = _regenerate(subset_fixture, tmp_path, make_spike_detector, database=database)
    lines = list(parse_report(run.text).section("software, data and settings").lines)
    index = lines.index("| Database | MIT-BIH Arrhythmia Database, version 1.0.0 |")

    assert MITDB.licence == ODC_BY_1_0
    assert lines[index + 1] == (
        "| Database licence | Open Data Commons Attribution License v1.0, "
        "https://opendatacommons.org/licenses/by/1-0/ |"
    )
    assert _lines_starting_with(run.text, "| Database licence |") == [
        f"| Database licence | {ODC_BY_TEXT} |"
    ]


@pytest.mark.requirement("SRS-016")
def test_report_states_the_software_identity(
    regenerated: Regenerated, running_software: Any, project_version: str
) -> None:
    """The software version with the identifier of the source code, and the runtime versions,
    checked as for SRS-012.

    Input: the subset report regenerated from the spike subset fixture by the package under
    test; the identifier computed by the test from the source files of that package (the six
    steps of architecture section 8.14, not the function of the software), the `__version__`
    literal, the Python version of the test process and the installed versions of numpy,
    scipy and wfdb.
    Expected: exactly one line `| Software | sinus-dsp <version>, source SHA-256
    <identifier> |` and one line `| Runtime | Python <major>.<minor>, numpy <v>, scipy <v>,
    wfdb <v> |`, with these values; the version is that of `dsp/pyproject.toml`; the results
    carry the same identity.
    """
    expected = running_software

    assert expected.version == project_version
    assert _lines_starting_with(regenerated.text, "| Software |") == [expected.software_row]
    assert _lines_starting_with(regenerated.text, "| Runtime |") == [expected.runtime_row]
    software = regenerated.results.software
    assert (software.version, software.source_sha256) == (expected.version, expected.source_sha256)
    assert (software.python, software.runtime) == (expected.python, expected.runtime)


@pytest.mark.requirement("SRS-016")
def test_report_states_the_settings_of_srs_007(
    regenerated: Regenerated, subset_fixture: Any, parse_report: Callable[[str], Any]
) -> None:
    """Detection runs with the settings of SRS-007, and the report states them.

    Input: the subset report regenerated from the spike subset fixture with the default
    settings. Channel 0 of each record holds the spikes of its design; channel 1 is flat (a
    detection on it would give TP 0).
    Expected: the results carry channel 0 and 60 Hz; the detector was called once per subset
    record, on 151200 samples at 360 Hz with the 60 Hz setting; the counts are those of
    channel 0 (each record's TP as designed); the rows "Signal" and "Mains interference
    filter" are "first stored signal of each record (channel 0)" and "60 Hz"; the row
    "Matching" is the documented description of the evaluation of SRS-008.
    """
    report = parse_report(regenerated.text)
    table = report.section("results per record").table_with_row("100")

    assert regenerated.results.settings == EvaluationSettings(channel=0, mains_hz=60)
    assert regenerated.calls == ((151200, 360.0, 60),) * 6
    for record in subset_fixture.subset_records():
        assert table.row(record.name)[2] == str(record.tp)
    assert _item(report, "Signal") == "first stored signal of each record (channel 0)"
    assert _item(report, "Mains interference filter") == "60 Hz"
    assert _item(report, "Matching") == MATCHING


# --------------------------------------------------------------------------------------------
# What was not scored because of ventricular flutter or fibrillation episodes
# --------------------------------------------------------------------------------------------


@pytest.mark.requirement("SRS-016")
def test_report_states_what_was_not_scored(
    regenerated: Regenerated, subset_fixture: Any, parse_report: Callable[[str], Any]
) -> None:
    """The figures on the ventricular flutter episodes, for the subset record that has them.

    Input: the subset report regenerated from the spike subset fixture. Record 207 has two
    episodes: 36000–43200 (before 5:00) and 115200–124350 (after 5:00) with 25 reference
    beats, two unpaired detections and a flutter wave `!` inside the second; the other five
    records have none.
    Expected, in "Segments not scored": the documented introduction; a table with the
    columns Record, Episodes in the record, Episodes from 5:00, Duration from 5:00 (s),
    Reference beats not scored, Detections not scored, and the single row 207, 2, 1, 25.4
    (9151 samples at 360 Hz), 25, 2; the paragraph on flutter waves with 0.
    """
    section = parse_report(regenerated.text).section("segments not scored")
    tables = section.tables()
    record = subset_fixture.records["207"]

    assert NOT_SCORED_SENTENCE in section.lines
    assert len(tables) == 1
    assert tables[0].header == (
        "Record",
        "Episodes in the record",
        "Episodes from 5:00",
        "Duration from 5:00 (s)",
        "Reference beats not scored",
        "Detections not scored",
    )
    assert tables[0].rows == (("207", "2", "1", "25.4", "25", "2"),)
    assert (record.vf_episodes, record.vf_samples_scored, record.reference_excluded) == (
        2,
        9151,
        25,
    )
    assert FLUTTER_SENTENCE.format(n=0) in section.lines


@pytest.mark.requirement("SRS-016")
def test_report_says_so_when_no_record_has_an_episode(
    tmp_path: Path,
    subset_fixture_without_episodes: Any,
    make_spike_detector: Callable[[], Any],
    parse_report: Callable[[str], Any],
) -> None:
    """A subset without any episode: the report says so instead of giving a table.

    Input: the subset fixture without episodes (record 207 replaced by a regular record).
    Expected: "Segments not scored" has the documented introduction, the sentence "No
    ventricular flutter or fibrillation episode is annotated in these records.", the flutter
    wave paragraph with 0, and no table.
    """
    run = _regenerate(subset_fixture_without_episodes, tmp_path, make_spike_detector)
    section = parse_report(run.text).section("segments not scored")

    assert NOT_SCORED_SENTENCE in section.lines
    assert NO_EPISODE_SENTENCE in section.lines
    assert FLUTTER_SENTENCE.format(n=0) in section.lines
    assert section.tables() == []
