"""Requirement tests of SRS-016: the subset report stored in the repository (RC-004).

SRS-016 (v0.7.1): the build compares the regenerated subset report with "the subset report
stored in the repository", `docs/validation/qrs-ec57-subset-report.md` (architecture, section
8.11). That stored report shall contain the items of SRS-012 for records 100, 105, 108, 119,
203 and 207, with the outcome of the verification of their files in place of the outcome of
the SRS-001 verification and without the pass or fail of the SRS-007 thresholds, and state
that it covers a subset of records for regression checking and is not the performance
evaluation of SRS-007.

Without data, the tests read the stored file: its statements, its items, the software that it
states (the identity of the package under test, computed by the test as for SRS-012), and the
consistency of its figures (statistics of SRS-011 recomputed from its counts, rankings
recomputed from its values). With the local MIT-BIH Arrhythmia Database (`needs_data`), the
check of the build is run on it and must pass, and the figures that follow from the reference
annotations alone (signals, scored reference beats, ventricular flutter episodes, files
verified) are recomputed by the test from the `.hea`, `.atr` and checksum list files with
wfdb, independently of the software.
"""

from __future__ import annotations

import hashlib
import re
from collections.abc import Callable, Sequence
from fractions import Fraction
from pathlib import Path
from typing import Any

import pytest

from sinus_dsp.evaluation.subset import check_subset_report

pytestmark = pytest.mark.usefixtures("forbid_network")

REPO = Path(__file__).resolve().parents[3]
STORED = REPO / "docs" / "validation" / "qrs-ec57-subset-report.md"
DATA_DIR = REPO / "data"
MITDB_PIN = "b61158a96d5f2ca80edfb354a9a66a6324836c390a84e1966dcee2b907d6be43"
SUBSET = ("100", "105", "108", "119", "203", "207")
STATEMENT = (
    "Technical evaluation only. Sinus is not a medical device; these results are not a "
    "clinical validation."
)
SUBSET_PARAGRAPH = (
    "This report covers records 100, 105, 108, 119, 203 and 207 of the MIT-BIH Arrhythmia "
    "Database. It is a regression check run on every change, not the performance evaluation "
    "against the targets, which uses all 48 records (qrs-ec57-report.md)."
)
ORIGIN = "Generated by dsp/scripts/subset_check.py; do not edit by hand."
SECTIONS = (
    "Software, data and settings",
    "Results per record",
    "Lowest sensitivity",
    "Lowest positive predictivity",
    "Segments not scored",
)
# The beat annotation codes of SRS-002.
BEAT_CODES = frozenset("N L R B A a J S V r F e j n E / f Q ?".split())
FIVE_MINUTES_360 = 108000


@pytest.fixture(scope="module")
def stored_text() -> str:
    """The stored subset report, read as UTF-8."""
    return STORED.read_bytes().decode("utf-8")


def _item(report: Any, label: str) -> str:
    table = report.section("software, data and settings").table_with_row(label)
    assert table.header == ("Item", "Value")
    return str(table.row(label)[1])


def _per_record(report: Any) -> dict[str, tuple[str, ...]]:
    table = report.section("results per record").table_with_row("100")
    assert table.header == ("Record", "Signal", "TP", "FN", "FP", "Se (%)", "+P (%)")
    return {row[0]: row for row in table.rows}


# --------------------------------------------------------------------------------------------
# Without data: statements, items, software, consistency
# --------------------------------------------------------------------------------------------


@pytest.mark.requirement("SRS-016")
def test_stored_report_states_the_current_software(stored_text: str, running_software: Any) -> None:
    """The stored report states the software under test, as the regenerated one would.

    Input: `docs/validation/qrs-ec57-subset-report.md`; the identifier of the source code of
    the package under test computed by the test (architecture 8.14), its `__version__`
    literal, and the versions of Python, numpy, scipy and wfdb of the environment that runs
    the test (the environment of `uv.lock`).
    Expected: exactly one line `| Software | sinus-dsp <version>, source SHA-256
    <identifier> |` and one line `| Runtime | Python <major>.<minor>, numpy <v>, scipy <v>,
    wfdb <v> |`, equal to those of the package under test and of this environment (a stored
    report that states another software would make the check of the build fail).
    """
    lines = stored_text.split("\n")

    assert [line for line in lines if line.startswith("| Software |")] == [
        running_software.software_row
    ]
    assert [line for line in lines if line.startswith("| Runtime |")] == [
        running_software.runtime_row
    ]


@pytest.mark.requirement("SRS-016")
def test_stored_report_contains_the_items_of_the_subset_report(
    stored_text: str, parse_report: Callable[[str], Any]
) -> None:
    """The stored report has the statements and items that SRS-016 requires.

    Input: `docs/validation/qrs-ec57-subset-report.md`.
    Expected: the title "# QRS detection: EC57 subset report for regression checking"; the
    statement of SRS-012, the subset paragraph naming the six records and the MIT-BIH
    Arrhythmia Database, and the origin line, before the first section; the sections
    "Software, data and settings", "Results per record", "Lowest sensitivity", "Lowest
    positive predictivity" and "Segments not scored", in this order, and no other (no
    performance targets, no noise stress test, no "pass" or "fail"); the database "MIT-BIH
    Arrhythmia Database, version 1.0.0"; the verification "verified: 28 files match the
    published SHA-256 checksum list (SHA256SUMS.txt, SHA-256 b61158a9…be43); records 100,
    105, 108, 119, 203, 207" (the pinned list of SRS-001); 6 records; channel 0; 60 Hz; one
    row per subset record in the results; UTF-8 text with line feeds, ending with one line
    feed.
    """
    data = STORED.read_bytes()
    report = parse_report(stored_text)
    first_section = min(i for i, level, _ in report.headings if level > 1)
    blocks = "\n".join(report.lines[1:first_section]).split("\n\n")

    assert report.lines[0] == "# QRS detection: EC57 subset report for regression checking"
    assert [b.strip("\n") for b in blocks if b.strip()] == [STATEMENT, SUBSET_PARAGRAPH, ORIGIN]
    assert [title for _, level, title in report.headings if level > 1] == list(SECTIONS)
    assert not re.search(r"\b(pass|fail)\b", stored_text, re.IGNORECASE)
    assert "Target" not in stored_text and "99.50" not in stored_text and "≥" not in stored_text
    assert _item(report, "Database") == "MIT-BIH Arrhythmia Database, version 1.0.0"
    assert _item(report, "Verification") == (
        "verified: 28 files match the published SHA-256 checksum list (SHA256SUMS.txt, "
        f"SHA-256 {MITDB_PIN}); records 100, 105, 108, 119, 203, 207"
    )
    assert _item(report, "Records") == "6"
    assert _item(report, "Signal") == "first stored signal of each record (channel 0)"
    assert _item(report, "Mains interference filter") == "60 Hz"
    assert list(_per_record(report)) == [*SUBSET, "Gross", "Average"]
    assert b"\r" not in data and data.endswith(b"\n") and not data.endswith(b"\n\n")


def _value(text: str) -> Fraction | None:
    return None if text == "not defined" else Fraction(text)


@pytest.mark.requirement("SRS-016")
def test_stored_report_figures_follow_from_its_counts(
    stored_text: str,
    parse_report: Callable[[str], Any],
    percent_text: Callable[[int, int], str],
    mean_percent_text: Callable[[Sequence[tuple[int, int]]], str],
) -> None:
    """The statistics of SRS-011 and the rankings of SRS-012 in the stored report agree with
    its per-record counts.

    Input: `docs/validation/qrs-ec57-subset-report.md`.
    Expected: for each of the six records, Se = TP / (TP + FN) and +P = TP / (TP + FP) in
    percent with two decimals (or "not defined"); the row "Gross" holds the summed counts and
    the gross values; the row "Average" the means of the defined per-record values, and the
    paragraph states how many are defined; each ranking lists, lowest first, at most five
    records with a defined value, ordered by value and then by record name, with the values
    of the table.
    """
    report = parse_report(stored_text)
    rows = _per_record(report)
    counts = {name: tuple(int(rows[name][i]) for i in (2, 3, 4)) for name in SUBSET}

    for name, (tp, fn, fp) in counts.items():
        assert rows[name][5:] == (percent_text(tp, tp + fn), percent_text(tp, tp + fp)), name
    tp, fn, fp = (sum(c[i] for c in counts.values()) for i in range(3))
    assert rows["Gross"] == (
        "Gross",
        "",
        str(tp),
        str(fn),
        str(fp),
        percent_text(tp, tp + fn),
        percent_text(tp, tp + fp),
    )
    se_pairs = [(c[0], c[0] + c[1]) for c in counts.values()]
    ppv_pairs = [(c[0], c[0] + c[2]) for c in counts.values()]
    assert rows["Average"] == (
        "Average",
        "",
        "",
        "",
        "",
        mean_percent_text(se_pairs),
        mean_percent_text(ppv_pairs),
    )
    n_se = sum(1 for _, d in se_pairs if d)
    n_ppv = sum(1 for _, d in ppv_pairs if d)
    assert (
        "The averages are the means of the defined per-record values: Se is defined for "
        f"{n_se} of 6 records, +P for {n_ppv} of 6 records."
    ) in report.section("results per record").lines
    for keyword, column, pairs in (
        ("lowest sensitivity", 5, se_pairs),
        ("lowest positive predictivity", 6, ppv_pairs),
    ):
        defined = sorted(
            (Fraction(100 * n, d), name) for name, (n, d) in zip(SUBSET, pairs, strict=True) if d
        )[:5]
        expected = [
            (str(rank), name, rows[name][column]) for rank, (_, name) in enumerate(defined, start=1)
        ]
        tables = report.section(keyword).tables()
        assert len(tables) == 1
        assert [tuple(row) for row in tables[0].rows] == expected, keyword


# --------------------------------------------------------------------------------------------
# With the local MIT-BIH Arrhythmia Database
# --------------------------------------------------------------------------------------------


@pytest.mark.needs_data
@pytest.mark.requirement("SRS-016")
def test_check_of_the_build_passes_on_the_local_database(tmp_path: Path) -> None:
    """The stored report is the one that the check regenerates from the reference data.

    Input: the local MIT-BIH Arrhythmia Database in `data/mitdb` (verified against the
    pinned checksum list), the stored report, and the check with all its defaults (settings
    of SRS-007, QRS detection of SRS-006), without download (`fetch=None`); a path for the
    regenerated report.
    Expected: the check passes, and the regenerated report is byte-identical to the stored
    report.
    """
    regenerated = tmp_path / "regenerated.md"

    check_subset_report(STORED, DATA_DIR, regenerated_path=regenerated, fetch=None)

    assert regenerated.read_bytes() == STORED.read_bytes()


def _episodes(others: Sequence[tuple[int, str]], n_samples: int) -> list[tuple[int, int]]:
    """Ventricular flutter episodes as SRS-008 defines them: from an onset `[` to the next
    offset `]`, both included; without an offset, to the end of the record."""
    episodes: list[tuple[int, int]] = []
    onset: int | None = None
    for sample, symbol in others:
        if symbol == "[" and onset is None:
            onset = sample
        elif symbol == "]" and onset is not None:
            episodes.append((onset, sample))
            onset = None
    if onset is not None:
        episodes.append((onset, n_samples - 1))
    return episodes


def _covered(episodes: Sequence[tuple[int, int]], first: int, last: int) -> set[int]:
    """Samples from ``first`` to ``last`` that lie inside at least one episode."""
    samples: set[int] = set()
    for onset, offset in episodes:
        samples.update(range(max(onset, first), min(offset, last) + 1))
    return samples


@pytest.mark.needs_data
@pytest.mark.requirement("SRS-016")
def test_stored_figures_match_the_reference_annotations(
    stored_text: str, parse_report: Callable[[str], Any]
) -> None:
    """The figures of the stored report that follow from the reference data alone.

    Input: the stored report; for each subset record, its header and reference annotation
    file in `data/mitdb`, read with wfdb by the test; the published checksum list.
    Expected:
    - the checksum list is the pinned one, and it names 28 files of the six records (the
      number that the row "Verification" states);
    - each record is sampled at 360 Hz, and its row gives the name of its first stored
      signal;
    - for each record, TP + FN equals the reference beats (codes of SRS-002) at or after
      5:00 that lie outside every ventricular flutter episode;
    - "Segments not scored" has a row for each record with at least one episode (207 only),
      with the number of episodes in the record, the episodes that reach 5:00 or later,
      their duration from 5:00 with the onset and offset samples (one decimal, in s), and
      the reference beats at or after 5:00 inside them; architecture 8.10 gives 6, 1, 97.9
      and 0 for record 207;
    - the flutter-wave paragraph gives the `!` annotations from 5:00 to the end of the
      records that lie outside every episode (a design figure of the report).
    """
    import wfdb

    folder = DATA_DIR / "mitdb"
    checksum_list = (folder / "SHA256SUMS.txt").read_bytes()
    listed = [line.split(maxsplit=1)[1].lstrip("*") for line in checksum_list.decode().splitlines()]
    subset_files = [
        p for p in listed if "/" not in p and any(p.startswith(f"{r}.") for r in SUBSET)
    ]
    report = parse_report(stored_text)
    rows = _per_record(report)
    not_scored: dict[str, tuple[str, ...]] = {}
    for table in report.section("segments not scored").tables():
        not_scored.update({row[0]: row for row in table.rows})
    expected_not_scored: dict[str, tuple[str, ...]] = {}
    flutter_waves = 0

    assert hashlib.sha256(checksum_list).hexdigest() == MITDB_PIN
    assert len(subset_files) == 28
    for name in SUBSET:
        header = wfdb.rdheader(str(folder / name))
        annotation = wfdb.rdann(str(folder / name), "atr")
        n = int(header.sig_len)
        assert float(header.fs) == 360.0
        assert rows[name][1] == header.sig_name[0], name
        items = list(zip((int(s) for s in annotation.sample), annotation.symbol, strict=True))
        episodes = _episodes([(s, a) for s, a in items if a in ("[", "]")], n)
        inside = _covered(episodes, 0, n - 1)
        scored = [
            s for s, a in items if a in BEAT_CODES and s >= FIVE_MINUTES_360 and s not in inside
        ]
        assert int(rows[name][2]) + int(rows[name][3]) == len(scored), name
        flutter_waves += sum(
            1 for s, a in items if a == "!" and FIVE_MINUTES_360 <= s <= n - 1 and s not in inside
        )
        if episodes:
            from_five = [e for e in episodes if e[1] >= FIVE_MINUTES_360]
            duration = len(_covered(episodes, FIVE_MINUTES_360, n - 1)) / 360.0
            beats_inside = sum(
                1 for s, a in items if a in BEAT_CODES and s >= FIVE_MINUTES_360 and s in inside
            )
            expected_not_scored[name] = (
                str(len(episodes)),
                str(len(from_five)),
                f"{duration:.1f}",
                str(beats_inside),
            )

    assert sorted(not_scored) == sorted(expected_not_scored)
    for name, expected in expected_not_scored.items():
        assert not_scored[name][1:5] == expected, name
    assert expected_not_scored["207"] == ("6", "1", "97.9", "0")
    assert (
        "Flutter-wave annotations outside ventricular flutter and fibrillation episodes, "
        f"in all records: {flutter_waves}."
    ) in report.section("segments not scored").lines
